:wrench: Effectテンプレートに継承部分を追加
ProjectTSB/Asset pull request #130
Opened 2024-04-04 04:26 UTC by haiiro2gou

2024-04-04 08:55 UTC, Lapis-LJA commented
https://discord.com/channels/742465492861845564/796678627793174539/1221420781431427204
継承するEffectはエフェクト/テンプレート(継承)みたいな感じで追加してもいいよねみたいな話がある

2024-04-05 16:41 UTC, haiiro2gou commented
とはいえ何かしら値を編集するなら同じテンプレートでもいいんじゃないかって気もするんだよね
mob/ex.2とかそうだし

2024-04-05 17:41 UTC, haiiro2gou commented
まあそうかぁ

2024-04-06 11:56 UTC, Lapis-LJA requested changes

2024-04-06 11:56 UTC, Lapis-LJA commented on .vscode/settings.json
> +                        "    # function asset:effect/extends",
継承すると分かってるしコメントアウト要らないかも

2024-04-06 15:37 UTC, Lapis-LJA approved these changes

2024-04-06 17:59 UTC, merged