[神器1089]反物質回転式多銃身機関銃を作成
ProjectTSB/Asset pull request #140
Opened 2024-04-12 05:03 UTC by quikku

2024-04-12 06:24 UTC, haiiro2gou requested changes

2024-04-12 06:24 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1089.antimatter_gatling_rifle/trigger/hit.mcfunction
> +    effect give @s slowness 1 2 true
これだと命中時しか移動速度下がらない気がする

2024-04-12 06:24 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1089.antimatter_gatling_rifle/trigger/3.main.mcfunction
> +
多分残骸だと思うので消しておいて

2024-04-12 08:07 UTC, quikku commented on Asset/data/asset/functions/artifact/1089.antimatter_gatling_rifle/trigger/hit.mcfunction
> +    effect give @s slowness 1 2 true
（なんでここに書いたんだ……）

2024-05-02 12:04 UTC, haiiro2gou approved these changes

2024-05-02 17:39 UTC, merged