⚖️ ハチ系Mobの仕様変更
ProjectTSB/Asset pull request #149
Opened 2024-04-24 15:22 UTC by Lapis-LJA

2024-04-25 10:34 UTC, haiiro2gou approved these changes
かなりハチだよこれ！

2024-04-28 04:04 UTC, haiiro2gou requested changes
突進時の`minecraft:cloud`パーティクルの表示条件が二匹で異なるので統一してほしい

2024-04-28 17:47 UTC, haiiro2gou commented
playsoundも直してほしいかも
片方は突進開始、もう片方は突進終了のタイミングで音を出してるから揃えてほしい

2024-04-29 05:38 UTC, Lapis-LJA commented
あとで突進開始で揃える

2024-04-29 17:52 UTC, haiiro2gou commented
キラービーは突進開始時
凶暴な蜂は方向転換時になってる

2024-04-30 07:16 UTC, haiiro2gou approved these changes

2024-04-30 07:16 UTC, merged