【神器1043】ブラックホール・ミニを作成
ProjectTSB/Asset pull request #16
Opened 2023-12-10 11:09 UTC by EllaCoat

2023-12-29 03:23 UTC, haiiro2gou requested changes
気になったのはこの辺
- $T1.Distanceのリセット
- `trigger/schedule/3.1.search_mob_m.mcf` -> `trigger/schedule/3.1.search_mob.m.mcf`
- ~~`trigger/schedule/**`用のrejoin_process登録~~

2023-12-29 06:34 UTC, EllaCoat commented
rejoin_processはモブに対してしか行っていないのでいらないと判断

2023-12-29 06:38 UTC, haiiro2gou approved these changes
よさそう

2024-04-07 04:08 UTC, haiiro2gou requested changes
vfx関連のmcfの先頭行にfunction名の記述がないので直してほしい

2024-05-03 10:17 UTC, haiiro2gou approved these changes

2024-05-03 11:11 UTC, merged