【神器0536-0537】終夜のAttributeのUUIDを修正
ProjectTSB/Asset pull request #18
Opened 2023-12-12 06:07 UTC by EllaCoat

2023-12-12 08:16 UTC, quikku commented on Asset/data/asset/functions/artifact/0537.all_night_boots/give/2.give.mcfunction
> +    data modify storage asset:artifact CustomNBT set value {display:{color:1050959},HideFlags:64,Enchantments:[{id:"minecraft:protection",lvl:1s},{id:"minecraft:unbreaking",lvl:2s}],AttributeModifier
feetなら1,1,537,3だわ

2023-12-12 10:00 UTC, EllaCoat commented on Asset/data/asset/functions/artifact/0537.all_night_boots/give/2.give.mcfunction
> +    data modify storage asset:artifact CustomNBT set value {display:{color:1050959},HideFlags:64,Enchantments:[{id:"minecraft:protection",lvl:1s},{id:"minecraft:unbreaking",lvl:2s}],AttributeModifier
たしかにそうだったわ
ありがとう

2023-12-28 17:34 UTC, haiiro2gou approved these changes
よさそう

2024-04-03 10:04 UTC, haiiro2gou requested changes

2024-04-03 10:04 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0536.all_night_leggings/give/2.give.mcfunction
> +    data modify storage asset:artifact CustomNBT set value {Unbreaking:1b,display:{color:1050959},HideFlags:64,Enchantments:[{id:"minecraft:protection",lvl:1s}],AttributeModifiers:[{AttributeName:"ge
Unbreakableにしてほしい

2024-04-03 10:04 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0537.all_night_boots/give/2.give.mcfunction
> +    data modify storage asset:artifact CustomNBT set value {Unbreaking:1b,display:{color:1050959},HideFlags:64,Enchantments:[{id:"minecraft:protection",lvl:1s}],AttributeModifiers:[{AttributeName:"ge
同上

2024-04-23 14:34 UTC, Lapis-LJA commented
別で修正します

2024-04-23 14:34 UTC, closed without merging