[神器1029]罪を裁く黒骨を作成
ProjectTSB/Asset pull request #182
Opened 2024-05-19 14:00 UTC by quikku

2024-11-22 02:47 UTC, Lapis-LJA requested changes
時間が余計かかるだけだろうからObjectへの移行は考慮しないものとしてレビューした

2024-11-22 02:47 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1029.conviction_bone/give/2.give.mcfunction
> +    # data modify storage asset:artifact AttackInfo.AttackRange set value
攻撃範囲の情報書け

2024-11-22 02:47 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1029.conviction_bone/trigger/shot/hit.mcfunction
> +        execute as @e[tag=Enemy,distance=..2,sort=nearest,limit=1] run function api:damage/
type=#lib:livingつけてほしい

2024-11-22 02:47 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1029.conviction_bone/trigger/shot/shot.mcfunction
> +    execute if score @s SL.CoolTime matches 4.. if entity @e[tag=Enemy,distance=..2,sort=nearest,limit=1] run function asset:artifact/1029.conviction_bone/trigger/shot/hit
type=#lib:living

2024-11-22 02:47 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1029.conviction_bone/trigger/shot/summon.mcfunction
> +    scoreboard players set @e[type=marker,tag=SL.First,distance=..10,sort=nearest] SL.ShotTime 60
魚？？？

2024-11-22 02:47 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1029.conviction_bone/trigger/sword/hit.mcfunction
> +        data modify storage api: Argument.DamageType set value "Projectile"
DamageTypeって現状あったっけ...？

2024-11-22 03:18 UTC, quikku commented on Asset/data/asset/functions/artifact/1029.conviction_bone/trigger/sword/hit.mcfunction
> +        data modify storage api: Argument.DamageType set value "Projectile"
ないよな？なんだこれ？

2024-12-14 15:19 UTC, haiiro2gou approved these changes

2024-12-18 19:17 UTC, merged