赤石商人を作成
ProjectTSB/Asset pull request #20
Opened 2023-12-15 16:11 UTC by Lapis-LJA

2023-12-28 17:31 UTC, haiiro2gou approved these changes
よさそう

2023-12-28 17:32 UTC, haiiro2gou requested changes
全然よくねえ、register登録されてないわ

2023-12-28 17:34 UTC, haiiro2gou approved these changes
今度こそよさそう

2024-01-24 04:32 UTC, ChenCMD approved these changes

2024-01-24 04:32 UTC, merged