【神器1047】魂命の徽章を作成
ProjectTSB/Asset pull request #22
Opened 2023-12-19 07:36 UTC by EllaCoat

効果や説明等すべて完成した状態でコミット

2023-12-28 17:48 UTC, haiiro2gou requested changes
`_index.d.mcf`は消してね

2023-12-28 17:48 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1047.life_steal_emblem/trigger/2.check_condition.mcfunction
> +    execute unless score $T3.CurrentHP Temporary matches 251.. run tag @s remove CanUsed
```suggestion
    execute unless score $T3.CurrentHP Temporary matches 250.. run function asset:artifact/1047.life_steal_emblem/trigger/error_message
    execute unless score $T3.CurrentHP Temporary matches 250.. run tag @s remove CanUsed
```
25%以上だから250でよさそう

2024-01-06 04:38 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1047.life_steal_emblem/trigger/2.check_condition.mcfunction
> +    execute unless score $T3.CurrentHP Temporary matches 251.. run tag @s remove CanUsed
普通に考えりゃ死ぬとまずいか

2024-01-06 14:40 UTC, haiiro2gou approved these changes

2024-02-20 04:53 UTC, Lapis-LJA commented
これなんでeffectAssetじゃないの...?

2024-04-27 17:46 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1047.life_steal_emblem/trigger/3.main.mcfunction
> +    function lib:damage/modifier
メモ：こいつはあってもなくてもいい

2024-04-27 17:46 UTC, haiiro2gou requested changes
実装に問題はないが、EffectAsset送りにすべき

2024-07-16 10:13 UTC, haiiro2gou approved these changes
よさそう

2024-07-16 10:14 UTC, merged