【神器1048】サンダーストームを作成
ProjectTSB/Asset pull request #23
Opened 2023-12-20 12:51 UTC by EllaCoat

挙動、説明など完成
linterのエラーは function withを使用しているからです

2023-12-29 03:34 UTC, haiiro2gou requested changes
rejoin_processが必要そうに見える

2023-12-29 06:38 UTC, EllaCoat commented
scheduleはモブに対してしか行っていないのでrejoin_processはいらないと判断

2023-12-29 06:41 UTC, haiiro2gou approved these changes
じゃあよさそう

2024-01-08 14:23 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1048.thunder_storm/trigger/3.main.mcfunction
>      execute as @e[type=marker,tag=T4.MarkerInit,distance=..24] run scoreboard players operation @s T4.MPPer = $MPValue Temporary
被ってそう

2024-01-08 14:24 UTC, haiiro2gou requested changes
↑

2024-01-08 17:13 UTC, haiiro2gou approved these changes

2024-04-07 04:24 UTC, haiiro2gou requested changes
vfx関連のmcfの先頭行にfunction名の記述がないので直してほしい

2024-05-03 11:13 UTC, haiiro2gou approved these changes

2024-05-03 12:13 UTC, merged