[神器898 & Effect261] 疾風のペンダント
ProjectTSB/Asset pull request #230
Opened 2024-07-28 10:45 UTC by Lapis-LJA

Fixed #228

2024-11-14 17:57 UTC, haiiro2gou requested changes

2024-11-14 17:57 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0898.gale_pendant/trigger/buff.mcfunction
> +    function api:entity/mob/effect/give
所持数0の場合が考慮されていない

2024-11-15 00:55 UTC, haiiro2gou requested changes

2024-11-15 00:55 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0898.gale_pendant/trigger/buff.mcfunction
> +    function api:entity/mob/effect/give
スタック0でこれが呼び出されてエラーが出そう

2024-11-15 00:57 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/0898.gale_pendant/trigger/buff.mcfunction
> +    function api:entity/mob/effect/give
一応、スタック0でも正常に動いた
それはそれとして、それ対策のためにreturnでそれが実行されないようにしたはず

2024-11-15 04:16 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0898.gale_pendant/trigger/buff.mcfunction
> +    function api:entity/mob/effect/give
対処されてたわ
すまねえ

2024-11-15 04:16 UTC, haiiro2gou approved these changes

2024-11-16 09:04 UTC, merged