[神器554-557] カタストロフィのリワーク
ProjectTSB/Asset pull request #235
Opened 2024-07-31 14:32 UTC by Lapis-LJA

Fix #106

2024-11-25 06:19 UTC, Lapis-LJA commented
現状、攻撃時に問答無用でバフのスタックが1加算されているが、一定ダメージ与える毎に変えたいところ

2024-12-08 16:15 UTC, haiiro2gou requested changes

2024-12-08 16:15 UTC, haiiro2gou commented on Asset/data/asset/tags/functions/effect/given.json
> -        "asset:effect/0203.secret_meat/_/given",
消えてんよ～

2024-12-08 16:15 UTC, haiiro2gou commented on Asset/data/asset/tags/functions/effect/register.json
> +        "asset:effect/0613.white_curse/_/register",
増えてんよ～

2024-12-08 16:15 UTC, haiiro2gou commented on Asset/data/asset/tags/functions/effect/tick.json
> +        "asset:effect/0613.white_curse/_/tick",
増えてんよ～

2024-12-08 16:27 UTC, haiiro2gou approved these changes

2024-12-08 16:28 UTC, merged