[神器1065] 魔弾の作成
ProjectTSB/Asset pull request #238
Opened 2024-08-05 08:26 UTC by Lapis-LJA

2024-12-08 15:58 UTC, haiiro2gou requested changes
魔弾、Object送り

2024-12-08 17:40 UTC, Lapis-LJA commented
マジで余裕ないんで後回しじゃダメ？

2024-12-09 15:36 UTC, haiiro2gou requested changes

2024-12-09 15:36 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1065.magic_bullet/trigger/loop/bullet/move.mcfunction
> +# プレイヤーを狙う状態かつ移動し始めてから1tick目(20)かつ、$Recursiveが1の時に強制的に中団
?

2024-12-09 15:36 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1065.magic_bullet/trigger/loop/bullet/damage/.mcfunction
> +    execute if entity @s[tag=TL.AimToPlayer,scores={TL.UseCount=7}] if entity @p[tag=Owner,tag=TL.TargetEntity] as @p[tag=Owner] run function asset:artifact/1065.magic_bullet/trigger/loop/bullet/dama
```suggestion
    execute if entity @s[tag=TL.AimToPlayer,scores={TL.UseCount=7}] as @p[tag=Owner,tag=TL.TargetEntity] run function asset:artifact/1065.magic_bullet/trigger/loop/bullet/damage/hit_myself
```

2024-12-09 15:38 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1065.magic_bullet/trigger/loop/bullet/move.mcfunction
> +# プレイヤーを狙う状態かつ移動し始めてから1tick目(20)かつ、$Recursiveが1の時に強制的に中団
マジで文字通りとしか言えない

2024-12-09 17:04 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1065.magic_bullet/trigger/loop/bullet/move.mcfunction
> +# プレイヤーを狙う状態かつ移動し始めてから1tick目(20)かつ、$Recursiveが1の時に強制的に中団
いや、「中団」ってなによ

2024-12-09 17:05 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1065.magic_bullet/trigger/loop/bullet/move.mcfunction
> +# プレイヤーを狙う状態かつ移動し始めてから1tick目(20)かつ、$Recursiveが1の時に強制的に中団
今気づいた

2024-12-09 17:06 UTC, haiiro2gou approved these changes

2024-12-09 17:06 UTC, merged