:recycle: エンド天候実装に伴う神器のリワーク
ProjectTSB/Asset pull request #265
Opened 2024-09-22 09:39 UTC by haiiro2gou

2024-09-22 10:00 UTC, Lapis-LJA requested changes

2024-09-22 10:00 UTC, Lapis-LJA commented on Asset/data/asset/functions/effect/0209.key_of_thunderbolt/register.mcfunction
> +    data modify storage asset:effect Description set value ['{"text":"雷属性の攻撃力が上昇する。"}']
雷属性与ダメージが大きく上昇する

2024-09-22 10:00 UTC, Lapis-LJA commented on Asset/data/asset/functions/effect/0252.key_of_another_world/register.mcfunction
> +    data modify storage asset:effect Description set value ['{"text":"全属性の攻撃力が上昇する。"}']
与ダメージが上昇する

2024-09-25 12:13 UTC, Lapis-LJA requested changes
resolvedになってたから再度書くけど、registerのDescripition、コメントした通りに変えといてね
Effectの説明の規格化の参考
https://discord.com/channels/742465492861845564/807449634770386964/1265171971700817941

2024-09-25 16:17 UTC, haiiro2gou commented
間に「の」がないの不自然じゃね？
まあいいけどさ

2024-09-26 00:20 UTC, Lapis-LJA approved these changes
良さげな気がする

2024-09-26 02:08 UTC, Lapis-LJA commented
> 間に「の」がないの不自然じゃね？ まあいいけどさ

言葉が足りてなかった、registerだけ変えてくれればよかったんよね（

2024-09-26 04:12 UTC, merged