フルストゥーカをオブジェクトAssetに以降
ProjectTSB/Asset pull request #289
Opened 2024-10-20 06:38 UTC by quikku

2024-11-22 02:29 UTC, Lapis-LJA requested changes

2024-11-22 02:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/0613.call_fulstuka/trigger/3.main.mcfunction
>      playsound entity.lightning_bolt.impact neutral @a ~ ~ ~ 0.7 0
神器側でneutralにするくらいならフルストゥーカ側にinitで演出として入れた方がよさそう

2024-11-22 02:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/1050.call_fulstuka/tick/1.skill_gun/5.damage.mcfunction
ついでに嘘の属性コメントを直しておこう

2024-11-22 02:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/1050.call_fulstuka/tick/2.skill_melee/3.slash.mcfunction
嘘の属性コメントを直そう(2)

2024-11-22 02:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/1050.call_fulstuka/tick/return.mcfunction
playsoundはhostileだからneutralにしよう

2024-11-22 02:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/1050.call_fulstuka/tick/spreadteleport.mcfunction
Mobにあった時からそうだったみたいだけど、ファイル名が命名規則に反してそう

2024-12-08 15:35 UTC, haiiro2gou requested changes

2024-12-08 15:35 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0613.call_fulstuka/trigger/3.main.mcfunction
> +    data modify storage api: Argument.FieldOverride.Rotation set from entity @s Rotation
拾うのはYawだけで良さそう

2024-12-08 15:35 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1050.call_fulstuka/tick/4.skill_active.mcfunction
> +    execute if entity @s[tag=1050.SkillMelee] run function asset:object/1050.call_fulstuka/tick/2.skill_melee/1.skill_melee
🤔

2024-12-08 15:41 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1050.call_fulstuka/_index.d.mcfunction
> +    #declare tag 1050.Fulstuka
これ使ってなくね

2024-12-09 14:24 UTC, haiiro2gou approved these changes

2024-12-09 14:24 UTC, merged