[神器1122]守護者の鉄塊を作成
ProjectTSB/Asset pull request #327
Opened 2024-10-27 08:45 UTC by quikku

2024-10-30 04:57 UTC, ChenCMD requested changes

2024-10-30 04:57 UTC, ChenCMD commented on Asset/data/asset/functions/artifact/1122.guardian_ironlump/trigger/dis_equip/.mcfunction
> +execute if data storage asset:context id{auto:1122} run function asset:artifact/1122.guardian_ironlump/trigger/dis_equip/main
MUST: if がおかしい

2024-10-30 04:57 UTC, ChenCMD commented on Asset/data/asset/functions/artifact/1122.guardian_ironlump/trigger/dis_equip/main.mcfunction
> +    function api:modifier/defense/base/remove
MUST: 複数個持った後に一つ外したときにも動くのでこれだとまずい

2024-11-10 09:24 UTC, Lapis-LJA requested changes

2024-11-10 09:24 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1122.guardian_ironlump/trigger/3.main.mcfunction
> +    playsound entity.iron_golem.death hostile @a ~ ~ ~ 1 2
hostileではなくplayerが正しそう

2024-11-10 09:37 UTC, Lapis-LJA requested changes

2024-11-10 09:37 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1122.guardian_ironlump/trigger/3.main.mcfunction
> +    data modify storage api: Argument.UUID set value [I;1,1,1122,6]
細かいけど、最後の6は0の方がいい
(6はhead、0は基本的にhotbar用に使ってる)

2024-11-10 09:39 UTC, quikku commented on Asset/data/asset/functions/artifact/1122.guardian_ironlump/trigger/3.main.mcfunction
> +    data modify storage api: Argument.UUID set value [I;1,1,1122,6]
7だよ！！！！

2024-11-10 09:40 UTC, Lapis-LJA approved these changes
よさそ

2024-12-12 19:19 UTC, merged