【Object2063】汎用円形ダメージエリアを作った
ProjectTSB/Asset pull request #334
Opened 2024-10-30 17:42 UTC by EllaCoat

色、サイズ、表示時間を調整できるように作った。
もっと良いテクスチャを用意できる人募集中。

2024-10-31 04:32 UTC, Lapis-LJA requested changes

2024-10-31 04:32 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2063.damage_area/tick/.mcfunction
> +    execute if score $2063.Temp General.Object.Tick <= @s General.Object.Tick run kill @s
勘違いだったら申し訳ないけど、この処理は$2063.Tempが汎用Tick以下ならkillじゃない？
本来は$2063.Temp >= Tickの時にkillしたいように見える

2024-10-31 04:32 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2063.damage_area/tick/.mcfunction
> +    execute if score $2063.Temp General.Object.Tick <= @s General.Object.Tick run kill @s
$2063.Tempがリセットされていない

2024-11-10 00:27 UTC, EllaCoat commented on Asset/data/asset/functions/object/2063.damage_area/tick/.mcfunction
> +    execute if score $2063.Temp General.Object.Tick <= @s General.Object.Tick run kill @s
いや、$2063.Tempはキルする時間だから、$2063.Temp以上になったらキルするであってる

2024-11-10 00:28 UTC, EllaCoat commented on Asset/data/asset/functions/object/2063.damage_area/tick/.mcfunction
> +    execute if score $2063.Temp General.Object.Tick <= @s General.Object.Tick run kill @s
直しとく

2024-11-10 00:31 UTC, EllaCoat commented on Asset/data/asset/functions/object/2063.damage_area/tick/.mcfunction
> +    execute if score $2063.Temp General.Object.Tick <= @s General.Object.Tick run kill @s
$2063.Temp >= Tickの時にkillだったらそれ召喚した直後にキルされるやん

2024-11-10 05:13 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2063.damage_area/tick/.mcfunction
> +    execute if score $2063.Temp General.Object.Tick <= @s General.Object.Tick run kill @s
ああそうだわ、私のミスだわこれ

2024-11-10 08:42 UTC, Lapis-LJA approved these changes
良さげになったっぽい

2024-11-10 08:44 UTC, merged