[123mob
ProjectTSB/Asset pull request #347
Opened 2024-11-10 07:32 UTC by quikku

2024-11-19 02:35 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0123.lexiel_v3/load.mcfunction
> +    scoreboard objectives add 3F.Tick dummy
実はTickはGeneral.Mob.Tickでいいかも

2024-11-19 02:49 UTC, Lapis-LJA requested changes
@p[] に関してはどっちでもいいけど、一応気になったので指摘した
他にも何個かあったけど多すぎたのでスルーした

2024-11-19 02:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0123.lexiel_v3/summon/.mcfunction
> +    summon skeleton ~ ~ ~ {Tags:["MobInit","AlwaysInvisible"],PersistenceRequired:1b,Silent:1b,NoAI:1b,DeathLootTable:"asset:mob/death/0123.lexiel_v3"}
DeathLoottableは不要になったから消しちゃってほしい

2024-11-19 02:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0123.lexiel_v3/tick/.mcfunction
> +    execute if score @s 3F.Tick matches 0 unless entity @p[gamemode=!spectator,distance=..100] run scoreboard players set @s 3F.Tick -60
天使だからプレイヤーは常に周囲にいるものじゃない？

2024-11-19 02:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0123.lexiel_v3/tick/01.skill_sword/main.mcfunction
> +    execute if score @s 3F.Tick matches 0 facing entity @p[] feet run function asset:mob/0123.lexiel_v3/tick/common/tp
この [] いらんやろ

2024-11-19 02:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0123.lexiel_v3/tick/02.skill_sword2/main.mcfunction
> +    execute if score @s 3F.Tick matches 7 at @p[] rotated ~ 0 positioned ^ ^ ^2 run function asset:mob/0123.lexiel_v3/tick/common/spread_tp
@p[]

2024-11-19 02:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0123.lexiel_v3/tick/03.skill_sword3/main.mcfunction
> +    execute if score @s 3F.Tick matches 1060 at @p[] rotated ~ 0 positioned ~ ~1 ~ positioned ^ ^ ^1 run function asset:mob/0123.lexiel_v3/tick/03.skill_sword3/skill_move
@p[]

2024-11-19 02:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0123.lexiel_v3/tick/common/slash.mcfunction
> +        data modify storage api: Argument.Damage set value 25.37f
一応聞くけどこのダメージは何...?

2024-11-19 02:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0123.lexiel_v3/tick/common/slash3.mcfunction
> +# 斬撃エフェクト（これ実行する前に設定いれろよ！いれるんだぞ！！）
このコメント is 何

2024-11-19 02:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0123.lexiel_v3/tick/common/slash3.mcfunction
> +        data modify storage api: Argument.Damage set value 25.37f
謎のダメージ2

2024-11-19 02:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2103.lexiel_exprode/tick/hard_damage.mcfunction
> +    function lib:damage/reset
apiとlibが混ざってる

2024-11-19 02:49 UTC, Lapis-LJA commented on Asset/data/asset/loot_tables/mob/death/0123.lexiel_v3.json
Loottableは消しといてね

2024-11-19 02:50 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0123.lexiel_v3/summon/.mcfunction
> +    summon skeleton ~ ~ ~ {Tags:["MobInit","AlwaysInvisible"],PersistenceRequired:1b,Silent:1b,NoAI:1b,DeathLootTable:"asset:mob/death/0123.lexiel_v3"}
DeathLootTable:"empty" にしてほしい 何も落とさなくなるから

2024-12-09 17:08 UTC, quikku commented
@p[]の問題はdistance=..100とgamemode=!spectatorいれることにしました

2024-12-14 15:06 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0123.lexiel_v3/tick/common/thunder/main.mcfunction
> +#> asset:mob/0123.lexiel_v3/tick/common/main
```suggestion
#> asset:mob/0123.lexiel_v3/tick/common/thunder/main
```

2024-12-14 15:07 UTC, haiiro2gou requested changes

2024-12-14 15:07 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0123.lexiel_v3/tick/03.skill_sword3/tacle.mcfunction
> +#> asset:mob/0123.lexiel_v3/tick/03.skill_sword3/tacle
```suggestion
#> asset:mob/0123.lexiel_v3/tick/03.skill_sword3/tackle
```

2024-12-15 09:38 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2105.lexiel_death/tick/drop.mcfunction
> +    function api:artifact/spawn/from_id
誓いの杖がなかった

2024-12-15 09:59 UTC, haiiro2gou commented
> 実はTickはGeneral.Mob.Tickでいいかも

これやってしまおう

2024-12-15 12:29 UTC, merged