[神器1021] ブレイブブックを作成
ProjectTSB/Asset pull request #351
Opened 2024-11-12 17:17 UTC by Chuzume

・レベル4召喚神器。現状だと単体限定とはいえ、手放しにしては妙に高いDPSが出ます。
・元々「コール: ブレイブナイト」って名前で作ってブランチが放置されていたものです。

2024-11-19 02:34 UTC, Lapis-LJA requested changes

2024-11-19 02:34 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/1058.brave_knight/tick/.mcfunction
> +    scoreboard players operation @e[type=marker,tag=1058.MoveMarkerInit,distance=..60,sort=nearest,limit=1] 1058.OwnerID = @s 1058.OwnerID
これマーカーにIDを付与する必要ある？
このmcf内で召喚してkillまでしちゃうから必要ない気がする

2024-12-04 10:17 UTC, haiiro2gou requested changes

2024-12-04 10:17 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1058.brave_knight/init/.mcfunction
> +    tag @s add 1058.Init
使ってなさそう

2024-12-04 10:17 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1058.brave_knight/tick/.mcfunction
> +    #declare tag MoveMarker
存在しないタグ

2024-12-04 10:17 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1058.brave_knight/tick/event/disapper.mcfunction
> +#> asset:object/1058.brave_knight/tick/event/disapper
誤字
```suggestion
#> asset:object/1058.brave_knight/tick/event/disappear
```

2024-12-04 10:17 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1058.brave_knight/tick/event/combo/damage.mcfunction
> +    damage @s 0
apiがやってくれるのでいらないはず

2024-12-04 10:17 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1058.brave_knight/tick/event/combo/damage.mcfunction
> +    function lib:damage/reset
いらない

2024-12-04 10:17 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1058.brave_knight/tick/event/combo/damage.mcfunction
> +    data remove storage lib: Argument
これもいらない

2024-12-04 10:20 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1058.brave_knight/_index.d.mcfunction
> +    #declare tag 1058.Spirit
使ってない

2024-12-12 08:52 UTC, merged