[モブ376]断罪者V2を作成
ProjectTSB/Asset pull request #367
Opened 2024-11-16 01:58 UTC by quikku

2024-11-22 02:40 UTC, Lapis-LJA requested changes

2024-11-22 02:40 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/death/.mcfunction
現状masterにはないけどボスドロ落とすようにしよう

2024-11-22 02:40 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/load.mcfunction
> +    scoreboard objectives add AG.Tick dummy
一応、AG.Tickの代わりにGeneral.Mob.Tickの方がよさそう

2024-11-22 02:40 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/tick/.mcfunction
> +    execute if score @s AG.Tick matches 0 unless entity @p[gamemode=!spectator,distance=..100] run scoreboard players set @s AG.Tick -60
天使だからプレイヤーが周囲に無いのは想定しなくてよさそう

2024-11-22 02:40 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/tick/06.skill_axe6/execute.mcfunction
> +    execute as @p run function api:data_get/health
これ、特に指定なしの@pだけどいいのか？

2024-11-22 02:40 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/tick/06.skill_axe6/grab.mcfunction
> +    playsound minecraft:ambient.nether_wastes.mood hostile @s
selectorが@sだから聞こえなさそう

2024-11-22 02:40 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/tick/07.skill_axe7/hard_explode.mcfunction
> +        data modify storage api: Argument.ElementType set value "Fire"
嘘属性なので直そう

2024-11-22 02:40 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2106.convict_dead/tick/.mcfunction
> +    #execute if score @s General.Object.Tick matches 64 run function asset:object/2106.convict_dead/tick/drop
これObject側で出して大丈夫な奴なの？

2024-11-22 06:11 UTC, Lapis-LJA reviewed
実は、as @e[tag=AG.AJ,AG.AJlink]はAJLInkだけでいいかも
AJLinkがついたentityはAG.AJがついてることがわかってるから
まぁ直す必要はないけど気になったので

2024-11-22 17:32 UTC, quikku commented on Asset/data/asset/functions/object/2106.convict_dead/tick/.mcfunction
> +    #execute if score @s General.Object.Tick matches 64 run function asset:object/2106.convict_dead/tick/drop
死体は動かないしええやろ

2024-11-24 16:12 UTC, Lapis-LJA requested changes
これと同じやり方でレクもやっといてくれ、何か質問あれば投げてくれ

2024-11-24 16:12 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/register.mcfunction
> +
天使抽象を継承しよう
```suggestion
# 継承 (int) (オプション)
    data modify storage asset:mob Extends append value 2000
    function asset:mob/extends

```

2024-11-24 16:12 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/death/.mcfunction
> +
super.deathを呼び出そう
```suggestion
# super.death呼び出し
    function asset:mob/super.death
    
```

2024-11-24 16:12 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/hurt/.mcfunction
> +
super.hurtを呼び出そう
```suggestion
# super.hurt呼び出し
    function asset:mob/super.hurt
    
```

2024-11-24 16:12 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/init/.mcfunction
> +
super.initを呼び出そう
```suggestion
# super.init呼び出し
    function asset:mob/super.init
    
```

2024-11-24 16:12 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0376.convict_v2/remove/.mcfunction
> +
super.removeを呼び出そう
```suggestion
# super.remove呼び出し
    function asset:mob/super.remove
    
```

2024-12-12 21:12 UTC, haiiro2gou requested changes

2024-12-21 03:06 UTC, Lapis-LJA approved these changes
Maybe よさそう

2024-12-21 05:57 UTC, haiiro2gou approved these changes

2024-12-21 05:58 UTC, merged