🚸 [MOB0046] 絶望の時計をリメイク
ProjectTSB/Asset pull request #376
Opened 2024-11-17 13:35 UTC by ChenCMD

これ以上の対応はまた声が上がってからでいいかな
Fix #211

2024-11-17 21:38 UTC, Lapis-LJA requested changes
DeathトリガーでClockHandがkillされていない

2024-11-17 21:50 UTC, Lapis-LJA requested changes

2024-11-17 21:50 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/common/beam/damage.mcfunction
> +        data modify storage api: Argument.Damage set value 20
コメントのダメージ数値が嘘

2024-11-17 21:50 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/common/wall_laser_clock/damage.mcfunction
> +# @within function asset:mob/0046.clock_of_despair/tick/skill/common/wall_laser_clock/fire
未使用？

2024-12-28 13:20 UTC, Lapis-LJA requested changes

2024-12-28 13:20 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0046.clock_of_despair/death/.mcfunction
>      function api:artifact/spawn/from_id
増えたボスドロも入れてね

2024-12-28 13:52 UTC, Lapis-LJA requested changes

2024-12-28 13:52 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/12_oclock.mcfunction
> +    kill @e[type=armor_stand,tag=1A.ClockHand]
deathトリガー呼ばれるんだしここには要らない説ない？

2024-12-28 13:53 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0046.clock_of_despair/tick/skill/12_oclock.mcfunction
> +    kill @e[type=armor_stand,tag=1A.ClockHand]
わかるな

2025-01-06 14:48 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0046.clock_of_despair/tick/3.skill_active.mcfunction
直さなくてもいいんだけど、このファイルだけ採番ついてるのが気になった

2025-01-06 16:10 UTC, Lapis-LJA approved these changes
多分よさそう

2025-01-06 16:11 UTC, merged