:bento: [神器1137-1140] パルスアーマーを作成
ProjectTSB/Asset pull request #386
Opened 2024-11-22 16:18 UTC by haiiro2gou

Blocked by ProjectTSB/TheSkyBlessing#1621

2025-04-16 10:45 UTC, Lapis-LJA requested changes

2025-04-16 10:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1138.over_pulse_bodyarmor/give/2.give.mcfunction
> +    data modify storage asset:artifact Lore set value ['{"text":"暫くダメージを受けていない場合、"}','{"text":"衝撃を吸収する電磁バリアを生成する。"}','{"text":"他部位を装備するとバリアはより強固になる。"}','{"text":"─ 電磁バリア 展開。","color":"gray","italic":
電磁バリアをN生成する 他部位~~ より強固になる(最大N)がいいかも

2025-04-16 10:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/effect/0337.night_vision_goggle/remove/.mcfunction
> +function asset:effect/super.remove
Implementがないかも

2025-04-18 15:01 UTC, ChenCMD requested changes

2025-04-18 15:01 UTC, ChenCMD commented on Asset/data/asset/functions/artifact/1137.over_pulse_headgear/register.mcfunction
> +data modify storage asset:artifact RarityRegistry[4] append value [1137,1138,1139,1140]
ブルーシャード頼むぜ

2025-04-19 05:27 UTC, Lapis-LJA reviewed
装備時のplaysoundは@.aのほうがいいかも？

2025-04-19 05:31 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1138.over_pulse_bodyarmor/tick/3.main.mcfunction
> +        function api:entity/player/absorption/add
最大体力比例か現在体力比例かどっちかにするべき

2025-04-19 12:28 UTC, Lapis-LJA approved these changes

2025-04-19 13:43 UTC, merged