[神器562] ハートランド頭のトリガーを削除
ProjectTSB/Asset pull request #41
Opened 2024-01-05 14:25 UTC by Lapis-LJA

2024-01-06 04:27 UTC, haiiro2gou reviewed
トリガーを脚と足に合わせてpassiveにした方がいい気もする

2024-01-06 10:04 UTC, haiiro2gou requested changes
↑

2024-01-06 10:05 UTC, Lapis-LJA commented
これ、胴体だけpassiveにすべきなんじゃ？

2024-01-06 10:11 UTC, haiiro2gou commented
そういえば、MPCostはないとエラーを吐きますね…

2024-01-06 10:12 UTC, haiiro2gou commented
> これ、胴体だけpassiveにすべきなんじゃ？

Triggerを外すことはできないからかと

2024-04-23 14:34 UTC, haiiro2gou approved these changes
ええんちゃう

2024-04-23 14:35 UTC, haiiro2gou requested changes
誤approve

2024-05-02 18:31 UTC, haiiro2gou approved these changes

2024-05-02 18:54 UTC, merged