[モブ377]灰の守護者V2
ProjectTSB/Asset pull request #412
Opened 2024-11-29 17:13 UTC by quikku

CBTで色々どうにかしてください

2024-12-04 11:08 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0377.grey_guardian_v2/register.mcfunction
> +    data modify storage asset:mob Health set value 999
999！！！！！！！！！！！！！！！

2024-12-05 15:20 UTC, haiiro2gou requested changes
灰守護v1

2024-12-05 15:20 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0377.grey_guardian_v2/tick/common/spread_tp.mcfunction
> +#> asset:mob/0377.grey_guardian_v2/tick/common/spread_tp
つかってないね

2024-12-09 16:04 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0377.grey_guardian_v2/hurt/.mcfunction
> +function asset:mob/super.hurt
hurtトリガーを作ってないなら自動的に天使抽象の処理が実行されるため必要ない
灰守護v2はhurtトリガーを作ってるので必要

今回の場合は演出を後で作るのでこのままでいい

2024-12-09 17:07 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0377.grey_guardian_v2/hurt/.mcfunction
> +function asset:mob/super.hurt
後付け予定なのであれば、了解

2024-12-09 17:08 UTC, haiiro2gou approved these changes

2024-12-09 17:09 UTC, merged