[mob378]赤騎士V3を作成
ProjectTSB/Asset pull request #438
Opened 2024-12-08 18:23 UTC by quikku

演出適当だったりするのは後々に回す

2024-12-09 18:27 UTC, haiiro2gou requested changes
個人的にはスキル2番が少しだけ気になってる
後ろに出る斬撃が歩いてても避けれるなぁって

2024-12-09 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0378.red_knight_v3/tick/skill_select.mcfunction
> +    execute if score @s AI.Skill matches 7.. run scoreboard players set @s AI.Skill 1
スキップの要素を鑑みると
-6した方が適切に思える

2024-12-09 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0378.red_knight_v3/tick/common/summon_knife.mcfunction
> +    #declare tag RotarionMaker
一応誤字
実装に影響はないが…

2024-12-09 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0378.red_knight_v3/tick/02.skill_plunge/tp.mcfunction
> +    execute at @s rotated ~ 0 run tp @e[type=item_display,tag=AI.AJ,tag=AI.AJLink,distance=..100,sort=nearest,limit=1] ~ ~ ~ ~ ~
`asset:mob/0378.red_knight_v3/tick/common/absolute_tp` を使っていないのはなぜ？

2024-12-09 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0378.red_knight_v3/tick/05.skill_jump/tp.mcfunction
> +    execute at @s rotated ~ 0 run tp @e[type=item_display,tag=AI.AJ,tag=AI.AJLink,distance=..100,sort=nearest,limit=1] ~ ~ ~ ~ ~
こちらも

2024-12-09 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0378.red_knight_v3/tick/common/absolute_tp.mcfunction
> +#> asset:mob/0378.red_knight_v3/tick/common/tp
ファイル名と一致していない

2024-12-09 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0378.red_knight_v3/tick/06.skill_jump2/tp.mcfunction
> +    execute at @s rotated ~ 0 run tp @e[type=item_display,tag=AI.AJ,tag=AI.AJLink,distance=..100,sort=nearest,limit=1] ~ ~ ~ ~ ~
これも `absolute_tp` ?

2024-12-09 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0378.red_knight_v3/tick/06.skill_jump2/search_ground.mcfunction
> +#> asset:mob/0378.red_knight_v3/tick/06.skill_jump2/search_ground
空ファイル

2024-12-09 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0378.red_knight_v3/tick/90.tp/skill_move.mcfunction
> +    scoreboard players operation $Random Temporary %= $4 Const
バイアス付きのほうがいいかも

2024-12-09 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0378.red_knight_v3/tick/90.tp/main.mcfunction
> +    execute if score @s AI.Tick matches 21 if predicate api:global_vars/difficulty/min/hard run data modify storage lib: Argument.Bounds set value [[5d,5d],[0d,0d],[5d,5d]]
処理順が逆かも

2024-12-09 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0378.red_knight_v3/_index.d.mcfunction
> +    #declare tag AI.Hit
これ使ってないね

2024-12-12 17:47 UTC, quikku commented
> 個人的にはスキル2番が少しだけ気になってる 後ろに出る斬撃が歩いてても避けれるなぁって

低HP状態でもなる？そうじゃないなら放置でもまあいい

2024-12-12 18:08 UTC, quikku commented on Asset/data/asset/functions/mob/0378.red_knight_v3/tick/02.skill_plunge/tp.mcfunction
> +    execute at @s rotated ~ 0 run tp @e[type=item_display,tag=AI.AJ,tag=AI.AJLink,distance=..100,sort=nearest,limit=1] ~ ~ ~ ~ ~
タグが必要だったから
今思えばこれ同じの二箇所使ってるんだしコモン化するべき

2024-12-12 20:28 UTC, haiiro2gou commented
> > 個人的にはスキル2番が少しだけ気になってる 後ろに出る斬撃が歩いてても避けれるなぁって
> 
> 低HP状態でもなる？そうじゃないなら放置でもまあいい

一発掠るかどうかだね

2024-12-12 20:35 UTC, haiiro2gou requested changes
忘れ物 @1

2024-12-12 20:45 UTC, haiiro2gou approved these changes

2024-12-12 20:46 UTC, merged