[Object2113] 汎用長方形ダメージエリアを作成
ProjectTSB/Asset pull request #442
Opened 2024-12-09 18:45 UTC by Lapis-LJA

2024-12-10 11:32 UTC, haiiro2gou requested changes
汎用Objectなので激辛添削

2024-12-10 11:32 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.ScaleZ set value 20f
配列じゃダメ？
`[5.0f, 20.0f]` とか `[5.0f, 20.0f, 0.01f]` の方が召喚側が実装しやすいと思うんだけど

2024-12-10 11:32 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
発動までのtick数がズレるのであまり好感を持てない
敵側のスキルって一定tick後に発動、みたいな感じで制御されてるから

2024-12-10 11:32 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +    execute store result storage asset:context this.TranslationZ float 0.05 run data get storage asset:context this.ScaleZ 10
`Transformation` な気がする

2024-12-10 11:32 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.RotationX set value 0.0f
これは共通Objectだから言っちゃうけど
Yawの方が分かるんじゃねえかな

もしくはRotationにしてPitchも反映するようにしてしまうか

2024-12-10 11:32 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.Duration set value 20
`Interpolation` って入れるべきかも

2024-12-10 11:32 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.KillTick set value 50
`Tick` でよくない？

2024-12-10 11:34 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.ScaleZ set value 20f
厚さの設定要らんでしょ

2024-12-10 11:35 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
displayの仕様で3tickずらさないと終わるんだよね

2024-12-10 11:36 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.KillTick set value 50
KillTickの方が自明じゃないか？

2024-12-10 11:37 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.ScaleZ set value 20f
それと、scaleなのに要素数が2なのはどうなの?という気持ち

2024-12-10 12:49 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.KillTick set value 50
使う側は表示時間でしかないから

2024-12-10 12:49 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.KillTick set value 50
むしろこっちの方がDurationまである

2024-12-10 13:19 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
Object2063 (汎用円形予告) みたいに拡大しきった後に
何tickか置いて消えるみたいなことはできないの？

2024-12-10 20:32 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.RotationX set value 0.0f
私個人としては直感的ではないけど、皆的にはどうなんだろう

2024-12-11 13:36 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.RotationX set value 0.0f
これは適当言い過ぎだったかも
よくよく考えたらマイクラに出てこねえわ

2024-12-11 14:32 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
それのためのKillTickなんよ すぐ消すこともできるし暫く残るようにもできる

2024-12-11 14:57 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +    execute store result storage asset:context this.TranslationZ float 0.05 run data get storage asset:context this.ScaleZ 10
これは正しいはず

2024-12-11 15:00 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
ダメージが発生したタイミングでは消えてないのマズいと思うんですが

2024-12-11 15:22 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
Duration(伸びる時間)とKillTick(存在時間)は別の方が便利と思った、と実際に需要があると使用者から意見貰ったけどどうだろう

2024-12-11 19:00 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
そこじゃなくて
スキルの本発動(ダメージの発生)と予告の消滅がズレることに問題があるって話をしている

2024-12-11 19:05 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
KillTick自体を3tick分考慮して設定してもらうのがベストかー？

2024-12-11 19:14 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
それこそinitで合わせるべきでは

2024-12-11 19:14 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/register.mcfunction
> +    data modify storage asset:object Field.KillTick set value 50
Tickでいい気がしてきた

2024-12-11 19:15 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
う～ん...? 今は3tick分加算してるよね..?

2024-12-11 19:17 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
> う～ん...? 今は3tick分加算してるよね..?

これって消滅が3tick遅れるってことでいいんだよね

2024-12-11 19:18 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
そうだね、その3Tick分加算する奴を破壊すればいいって解釈でいい？

2024-12-11 19:19 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
破壊するとどういう挙動になる？

2024-12-11 19:19 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
指定されたKillTick後にこのObjectが消滅する

2024-12-11 19:20 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
> displayの仕様で3tickずらさないと終わるんだよね

すまん、これがどうなるのか聞きたかった

2024-12-11 19:24 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
加算する処理破壊後、Durationが20、KillTickが20の時に、3Tick目から予告が伸びていく都合上、伸び始めてから17tick後に消える

2024-12-11 19:26 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
召喚後のNBT反映のラグの都合ってことかな
であれば、KillTickを合わせる方を優先してほしいな

2024-12-11 19:27 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
init側でKillTick +3ってことでok?

2024-12-11 19:28 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
表現がよくなかった
Fieldに入力したKillTick後に確実に消すようにすることを優先してほしい

2024-12-11 19:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
ならこれで全部レビュー対応終わってるかな

2024-12-11 19:31 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2113.rectangle_announce/init/.mcfunction
> +
後今更思ったのだけど、「Duration (Interpolation) がないときにKillTickに合うように値を自動で入力する」か、「0を突っ込む」かのどっちかの形でデフォルトを設定するといいかも

2024-12-12 10:31 UTC, haiiro2gou approved these changes

2024-12-12 10:33 UTC, merged