Dev/uran2471 mob213 TerribleSonicBomberと愉快な仲間たちの追加
ProjectTSB/Asset pull request #443
Opened 2024-12-11 14:33 UTC by uran247

最低限動く版のプルリク

2024-12-13 05:54 UTC, haiiro2gou requested changes

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/attack_motion_prepare.mcfunction
> +execute if score $health Temporary matches ..9999 store result score $weapon_num Temporary run random value 1..4
- 難易度によって最大体力が変わるので体力割合を取得する処理をちゃんと実装したほうがよい
- 乱数はバイアス付きの方がユーザー体験がよいと思われる

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/attack_motion.mcfunction
> +
tick処理の冒頭でやっているので不要

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/attack_motion.mcfunction
> +
これはどっちでもいいけど、移動処理が共通なら切り出したほうが良さそう

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/cruise_motion.mcfunction
> +
この `at @s` って必要？

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/attack_motion.mcfunction
> +   #declare score_holder $use_waapon
```suggestion
   #declare score_holder $use_weapon
```
実装に影響はないけど誤字っぽい
(他も併せて修正してね)

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/use_weapon.mcfunction
> +
```suggestion
   #declare score_holder $use_weapon

```
此方も実装に影響がないけど誤字っぽい

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/escape_after_attack.mcfunction
> +
```suggestion
   #declare score_holder $use_weapon

```
ここも多分誤字

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/weapons/snakeeye_prepare.mcfunction
> +data modify storage asset:context this.storm_shadow.target_pos set from entity @p Pos
不要な処理に見える

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0214.drone/death/.mcfunction
> +stopsound @a[distance=..128] hostile minecraft:entity.bee.loop
他のドローンのエンジン音まで止めてそうだけど、なんとかならない？

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0214.drone/death/.mcfunction
> +function api:damage/modifier
```suggestion
# 両方の例を提示してるのでそのままコミットしないでね

# 自爆ドローンが攻撃者
function api:damage/modifier
# 天使が攻撃者
# apiでドローンを召喚する際に MobUUID をデータとして入れておく必要がある
data modify storage api: Argument.MobUUID set from storage asset:context this.MobUUID
function api:damage/modifier_manual
```
どっちか選んでほしい
自爆ドローンで `api: Argument.MobUUID` を使わないのは `api:damage/modifier` 時点で実行者が定まってるから

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0214.drone/tick/.mcfunction
> +execute if entity @p[tag=!PlayerShouldInvulnerable,distance=..1] run function asset:mob/0214.drone/tick/suicide
これ、2tick連続で自爆処理を回すことになる (suicide -> death) ので改善したほうがいいかも

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2082.storm_shadow/_index.d.mcfunction
> +    #declare
使わないならファイルごと削除してほしい

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2083.brimstone/_index.d.mcfunction
> +    #declare
使わないなら削除

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2083.brimstone/turn.mcfunction
> +$execute unless entity @p[scores={UserID=$(TargetPlayerID)},distance=..15] facing entity @p[scores={UserID=$(TargetPlayerID)}] eyes run tp @s ~ ~ ~ ~ ~
```suggestion
$execute if entity @p[scores={UserID=$(TargetPlayerID)},distance=15..] facing entity @p[scores={UserID=$(TargetPlayerID)}] eyes run tp @s ~ ~ ~ ~ ~
```
今の状態だと関係ないプレイヤーが近くにいるだけで追尾を止めてからこっちのほうがいい気がする

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2082.storm_shadow/tick/.mcfunction
> +
Damage API など、処理中に当該エンティティのスコアを取得、変更する処理があるので
消滅処理はtickの末尾に入れてほしいかな

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2083.brimstone/tick/.mcfunction
> +    kill @s[scores={General.Object.Tick=1000..}]
上で述べた通り
消滅処理はtickの末尾に入れてほしい

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2083.brimstone/kill/.mcfunction
> +kill @s
これも同様に
消滅処理は末尾に入れてほしい

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2082.storm_shadow/kill/.mcfunction
> +kill @s
これも同様に
消滅処理はtickの末尾に入れてほしい

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2084.snake_eye/_index.d.mcfunction
> +    #declare
上で述べた通り削除

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2084.snake_eye/tick/.mcfunction
> +    kill @s[scores={General.Object.Tick=1000..}]
上で述べた通り
消滅処理はtickの末尾に入れてほしい

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2084.snake_eye/kill/.mcfunction
> +kill @s
これも同様に
消滅処理は末尾に入れてほしい

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2087.patriot/_index.d.mcfunction
> +    #declare
上で述べた通り削除

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2087.patriot/tick/.mcfunction
> +    kill @s[scores={General.Object.Tick=1000..}]
上で述べた通り
消滅処理はtickの末尾に入れてほしい

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2088.patriot_launcher/load.mcfunction
> +# @within tag/function asset:object/load
未使用なので削除してほしい

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2088.patriot_launcher/_index.d.mcfunction
> +
削除

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2088.patriot_launcher/tick/tick_broken.mcfunction
> +execute if score $RepairPlayer Temporary matches 4.. run scoreboard players set $RepairValue Temporary 348
4人以上だと減ってる

2024-12-13 05:54 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2088.patriot_launcher/tick/tick_broken.mcfunction
> +execute if entity @s[tag=PatriotLauncher.HitMissile] run scoreboard players add $RepairTime Temporary 10000
あまり起こらないとはいえ、 `$RepairTime` に上限値を設けるような処理をしたほうがいい気がする

2024-12-15 08:07 UTC, haiiro2gou requested changes

2024-12-15 08:07 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2088.patriot_launcher/tick/tick_active.mcfunction
> +    #declare tag
```suggestion
```

2024-12-15 08:09 UTC, haiiro2gou commented
上のresolveしてないやつも対応してほしい

2024-12-15 09:29 UTC, uran247 commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/cruise_motion.mcfunction
> +
12行目で向きを変えているため反映させるために必要

2024-12-15 09:30 UTC, uran247 commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/attack_motion.mcfunction
> +
今後攻撃モーション時に別移動にする可能性が高いため別にしておきたい

2024-12-15 09:31 UTC, uran247 commented on Asset/data/asset/functions/mob/0214.drone/death/.mcfunction
> +stopsound @a[distance=..128] hostile minecraft:entity.bee.loop
代案があるならすでにそうしているのでならない
他のドローンのエンジン音が止まったとしても別のドローンがtickしている限り即座に音が再再生されるため気にならないのは確認済み

2024-12-15 09:51 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0214.drone/death/.mcfunction
> +stopsound @a[distance=..128] hostile minecraft:entity.bee.loop
理解した

2024-12-15 09:51 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/attack_motion.mcfunction
> +
ok

2024-12-15 09:51 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/cruise_motion.mcfunction
> +
なるほどね

2024-12-15 12:37 UTC, haiiro2gou requested changes

2024-12-15 12:37 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0214.drone/tick/.mcfunction
> +execute unless entity @e[scores={ObjectID=2088},distance=..3] if entity @p[tag=!PlayerShouldInvulnerable,distance=..1] run function asset:mob/0214.drone/tick/suicide
言ってることが変わってしまって申し訳ないけど

tick -> 自爆
次のtick -> 自爆 -> death

の順で走ってて結局重複してるので

tick -> `api:mob/kill`
次のtick(素通り) -> death (ここで自爆)

という風にするべきかも

2024-12-15 17:47 UTC, uran247 commented on Asset/data/asset/functions/mob/0214.drone/tick/.mcfunction
> +execute unless entity @e[scores={ObjectID=2088},distance=..3] if entity @p[tag=!PlayerShouldInvulnerable,distance=..1] run function asset:mob/0214.drone/tick/suicide
それをやると次tickで範囲判定をしてしまいすり抜ける可能性が出てくるのでできない

2024-12-15 17:51 UTC, haiiro2gou approved these changes

2024-12-30 18:20 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/weapons/gatling_prepare.mcfunction
> +
これちゃんと当たるの？

2024-12-30 18:22 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/motions/attack_motion_prepare.mcfunction
> +#> asset:mob/0213.terrible_sonic_bomber/tick/motions/attack_motion_prepare
`motions` 以下のファイルが全部インデント3になってる

2024-12-31 06:41 UTC, uran247 commented on Asset/data/asset/functions/mob/0213.terrible_sonic_bomber/tick/weapons/gatling_prepare.mcfunction
> +
あたる

2024-12-31 07:14 UTC, haiiro2gou approved these changes

2024-12-31 07:14 UTC, merged