[神器1055] 海淵の羅針盤を作成
ProjectTSB/Asset pull request #46
Opened 2024-01-07 05:22 UTC by Lapis-LJA

2024-01-07 07:09 UTC, haiiro2gou requested changes
kb耐性の説明文と実際の効果が一致してない

2024-01-07 07:20 UTC, haiiro2gou approved these changes

2024-04-28 04:40 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1055.compass_of_sea_abyss/give/2.give.mcfunction
> +    data modify storage asset:artifact Lore set value ['{"text":"発動時、現在体力の10%分のダメージを受ける。","color":"white"}','{"text":"この効果での被ダメージ2につきMPを2回復し","color":"white"}','{"text":"周囲の敵5体へ120ダメージを与える。","color":
現在体力の10%を消費して、体力を2消費するごとに～
みたいなのもわかりやすいんじゃないかなって

2024-04-28 04:40 UTC, haiiro2gou requested changes

2024-04-28 04:40 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1055.compass_of_sea_abyss/trigger/3.main.mcfunction
> +    execute if score $SelfDamage Temporary matches ..19 run scoreboard players set $SelfDamage Temporary 20
最大値を固定してないぜ！

2024-04-28 08:07 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/1055.compass_of_sea_abyss/give/2.give.mcfunction
> +    data modify storage asset:artifact Lore set value ['{"text":"発動時、現在体力の10%分のダメージを受ける。","color":"white"}','{"text":"この効果での被ダメージ2につきMPを2回復し","color":"white"}','{"text":"周囲の敵5体へ120ダメージを与える。","color":
なんとなくだけど消費という表現は違うな〜くらいの気持ちがある

2024-04-28 08:15 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1055.compass_of_sea_abyss/give/2.give.mcfunction
> +    data modify storage asset:artifact Lore set value ['{"text":"発動時、現在体力の10%分のダメージを受ける。","color":"white"}','{"text":"この効果での被ダメージ2につきMPを2回復し","color":"white"}','{"text":"周囲の敵5体へ120ダメージを与える。","color":
じゃあいいかぁ

2024-04-28 08:19 UTC, haiiro2gou approved these changes

2024-04-28 09:03 UTC, merged