:bento: [Mob77] コーラスゾンビーを作成
ProjectTSB/Asset pull request #464
Opened 2024-12-16 15:21 UTC by haiiro2gou

2024-12-16 22:28 UTC, quikku commented on Asset/data/asset/functions/mob/0077.chorus_zombie/attack/.mcfunction
> +    execute as @a[tag=Victim,distance=..6] at @s if predicate lib:random_pass_per/30 run function asset:mob/0077.chorus_zombie/attack/teleport/
tpban入れたほうがいいかも
プレイヤー何しでかすかわからん

2024-12-17 03:25 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0077.chorus_zombie/attack/.mcfunction
> +    execute as @a[tag=Victim,distance=..6] at @s if predicate lib:random_pass_per/30 run function asset:mob/0077.chorus_zombie/attack/teleport/
わすれてたわ

2024-12-17 03:59 UTC, Lapis-LJA requested changes

2024-12-17 03:59 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0077.chorus_zombie/register.mcfunction
> +    # data modify storage asset:mob Defense set value
防具の分の防御力があるのでマイナスにして0にしよう

2024-12-17 21:48 UTC, Lapis-LJA approved these changes

2024-12-18 04:04 UTC, merged