ヘイローン作成
ProjectTSB/Asset pull request #473
Opened 2024-12-18 13:39 UTC by mokkkk

現時点である程度完成したため、途中までレビューできるようにPRを作成。

### 今後の変更予定
- 大技前の演出の調整
- 登場、退場演出の追加
- 当たり判定の位置調整（AJ側でやるのでレビューは不要なはず）

2025-01-02 10:39 UTC, haiiro2gou commented
レビュー進捗用
- [ ] ヘルファイア
- [ ] アダマントスパイク
- [ ] リヒトブリッツェン
- [ ] エンハンスドディザスター
- [ ] 移動
- [ ] 竜巻
- [ ] 薙ぎ払い火炎放射
- [ ] テンペスト
- [ ] ヘイルディザスター
- [ ] フレア
- [ ] 急降下
- [ ] パワーブレス

2025-01-02 10:44 UTC, haiiro2gou requested changes
一旦

2025-01-02 16:35 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2110.heiloang_heavenly_spike/load.mcfunction
> +    # scoreboard objectives add
未使用

2025-01-02 16:36 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2110.heiloang_heavenly_spike/init/.mcfunction
> +
全部この init 式予告召喚でいいんじゃないか、と今更思った

2025-01-02 16:40 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2110.heiloang_heavenly_spike/tick/damage.mcfunction
> +
めちゃめちゃ面倒だろうなとは思うんだけど
ダメージ後の演出の出現が遅いから不自然な気がした

この辺のどっちかをやってくれると嬉しい
- 拡大を前提にしてちょっとだけ出現を早める
- 先にターゲットして対象に後からダメージを与える

2025-01-02 16:40 UTC, haiiro2gou requested changes
Part 2

2025-01-02 16:45 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/richt_blitzen/.mcfunction
> +    execute if score @s BE.EventTimer matches 254.. run function asset:mob/0410.heiloang/tick/event/richt_blitzen/end
こういう追加行動で攻撃がズレる系は終了タイミングを別にしてもいいのではなかろうか

2025-01-02 16:50 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/richt_blitzen/.mcfunction
> +    # ハード以上：回転する雷を設置
私はランダムでもいいと思う

2025-01-02 16:51 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/richt_blitzen/.mcfunction
> +            execute if score @s BE.EventTimer matches 180 run playsound entity.lightning_bolt.impact hostile @a ~ ~ ~ 3 0.7
私はランダムもいいなと思う

2025-01-02 16:56 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2111.heiloang_thunder/load.mcfunction
> +    # scoreboard objectives add
未使用

2025-01-02 16:59 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2111.heiloang_thunder/tick/attack.mcfunction
> +
別に再定義する必要もなかった気がする

2025-01-02 17:09 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2112.heiloang_thunder_spin/tick/attack.mcfunction
> +
未使用

2025-01-02 17:09 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2112.heiloang_thunder_spin/tick/attack_0.mcfunction
> +
```suggestion
#> asset:object/2112.heiloang_thunder_spin/tick/attack_0
#
# Objectのtick時の処理
#
# @within asset:object/2112.heiloang_thunder_spin/tick/

```

2025-01-02 17:31 UTC, haiiro2gou requested changes
リヒトブリッツェン

2025-01-02 18:53 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/enhanced_disaster/.mcfunction
> +        execute if score @s BE.EventTimer matches 23 at @e[type=marker,tag=BE.CenterPosition] run function asset:mob/0410.heiloang/tick/event/enhanced_disaster/summon_circle
最初の範囲予告もObject内処理に送ってしまえばいいのではと思った

2025-01-02 18:55 UTC, haiiro2gou reviewed
エンハンスドディザスター

2025-01-02 19:00 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/move_after_ehd/.mcfunction
> +        execute if score @s BE.EventTimer matches 80 at @s run tp @s ^ ^ ^6 ~ ~
消えてるときに当たり判定が残ってるのは
（命中判定の引継ぎが解決してからとはいえ）要解決な気がする

2025-01-02 19:01 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/move_after_ehd/attack.mcfunction
> +    tag @a[tag=DXYZ] remove DXYZ
前述と同様

2025-01-02 19:06 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2117.heiloang_tornado/tick/attack.mcfunction
> +
一致してない

2025-01-02 19:07 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2117.heiloang_tornado/init/.mcfunction
> +# @within asset:object/alias/2117/init
未使用

2025-01-02 19:07 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2117.heiloang_tornado/load.mcfunction
> +    # scoreboard objectives add
未使用

2025-01-02 19:15 UTC, haiiro2gou reviewed
薙ぎ払い

2025-01-02 19:15 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/tornado/.mcfunction
> +
一応だけど
デバッグ系のリセット処理で中心点を向くようにしたほうがいいかもね

2025-01-02 19:15 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2122.heiloang_flame_vfx/init/.mcfunction
> +# @within asset:object/alias/2122/init
未使用

2025-01-02 19:22 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/tornado/particle_before.mcfunction
> +
```suggestion
#> asset:mob/0410.heiloang/tick/event/tornado/particle_before
#
# アダマントスパイク
#
# @within asset:mob/0410.heiloang/tick/event/tornado/

```

2025-01-02 19:24 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/tempest/summon.mcfunction
> +
未使用

2025-01-02 19:24 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/tempest/particle_before.mcfunction
> +
未使用

2025-01-02 19:28 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2121.heiloang_tempest/init/.mcfunction
> +# @within asset:object/alias/2121/init
未使用

2025-01-02 19:33 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/heil_disaster/attack_wind_burst.mcfunction
> +
未使用

2025-01-02 19:34 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/heil_disaster/particle_before.mcfunction
> +
未使用

2025-01-02 20:14 UTC, haiiro2gou requested changes
今回は未実装の 411 と 412 は見てないよ

スキル毎に別の時間にレビューしてる都合取っ散らかってるのは許してほしい
実装上の問題と余裕があれば改善してほしい細かいところのレビューが混ざってるので
気になる点なんかは聞いてくれれば早めに返答する

2025-01-02 20:14 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/power_breath_continue_1/end.mcfunction
> +    execute if score @s BE.Pb.Count matches ..1 run tag @s add BE.Skill.PowerBreath.End
C1再付与でよかった疑惑
Countが1なら中央を向きなおすようにすればendもいらないかも

2025-01-02 20:14 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/load.mcfunction
> +    # scoreboard objectives add
未使用

2025-01-02 20:14 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/tick/.mcfunction
> +
これも初手予告範囲表示するObjectでいいんじゃかろうか

2025-01-02 20:14 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/tick/damage_pursuit.mcfunction
> +        execute if predicate api:global_vars/difficulty/easy run tag @a[tag=DXYZ] remove DXYZ
検知が程々に重いので
出来る限り条件付きで検知をするようにしたほうがいい

2025-01-02 20:14 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/tick/damage_pursuit.mcfunction
> +    tag @a[tag=DXYZ] remove DXYZ
前述のとおり

2025-01-03 01:58 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/init/locator.mcfunction
> +    scoreboard players operation @s ForwardTargetMobUUID = @e[tag=BE.EntityRoot,limit=1] MobUUID
EntityRootはヘイローン本体のため問題ないと思います

2025-01-03 02:12 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/init/.mcfunction
> +        scoreboard players operation @s BE.Ehd.Thunder -= @s BE.Ehd.Water
対応しました

2025-01-03 02:12 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/util/remove_animation_tag.mcfunction
> +# 他エンティティに付与しているタグをすべて消去する
修正

2025-01-03 02:52 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/hellfire/attack.mcfunction
> +    execute store result storage api: Argument.FieldOverride.MobUUID int 1 run scoreboard players get @s MobUUID
削除しました

2025-01-03 02:52 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/hellfire/.mcfunction
> +        execute if score @s BE.EventTimer matches 10..279 at @p[tag=BE.MainTarget] rotated ~ 0 positioned ~ ~0.3 ~ run function asset:mob/0410.heiloang/tick/event/hellfire/particle_attack_area
直しました
ついでにヘルファイアの開始位置が頭に正確に合うように変更しました

2025-01-03 03:01 UTC, mokkkk commented on Asset/data/asset/functions/object/2107.heiloang_fireball/load.mcfunction
> +#> asset:object/2107.heiloang_fireball/load
削除しました

2025-01-03 03:16 UTC, mokkkk commented on Asset/data/asset/functions/object/2110.heiloang_heavenly_spike/load.mcfunction
> +    # scoreboard objectives add
削除しました

2025-01-03 03:20 UTC, mokkkk commented on Asset/data/asset/functions/object/2110.heiloang_heavenly_spike/tick/damage.mcfunction
> +
演出の出現を早めました

2025-01-03 03:27 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/richt_blitzen/.mcfunction
> +    execute if score @s BE.EventTimer matches 254.. run function asset:mob/0410.heiloang/tick/event/richt_blitzen/end
難易度で変えるようにしました

2025-01-03 04:04 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/richt_blitzen/.mcfunction
> +            execute if score @s BE.EventTimer matches 180 run playsound entity.lightning_bolt.impact hostile @a ~ ~ ~ 3 0.7
攻撃箇所をランダムにすると、場合によって難易度に極端な差が生まれそうなので固定が良いかなと思います

2025-01-03 04:38 UTC, mokkkk commented on Asset/data/asset/functions/object/2111.heiloang_thunder/load.mcfunction
> +    # scoreboard objectives add
削除しました

2025-01-03 04:47 UTC, mokkkk commented on Asset/data/asset/functions/object/2111.heiloang_thunder/tick/attack.mcfunction
> +
hitタグを削除しました

2025-01-03 05:03 UTC, mokkkk commented on Asset/data/asset/functions/object/2112.heiloang_thunder_spin/tick/attack.mcfunction
> +
削除しました

2025-01-03 05:06 UTC, mokkkk commented on Asset/data/asset/functions/object/2112.heiloang_thunder_spin/tick/attack_0.mcfunction
> +
修正しました

2025-01-03 05:12 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/enhanced_disaster/.mcfunction
> +        execute if score @s BE.EventTimer matches 23 at @e[type=marker,tag=BE.CenterPosition] run function asset:mob/0410.heiloang/tick/event/enhanced_disaster/summon_circle
一旦修正せず今のまま行きます

2025-01-03 05:14 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/move_after_ehd/attack.mcfunction
> +    tag @a[tag=DXYZ] remove DXYZ
修正しました

2025-01-03 05:20 UTC, mokkkk commented on Asset/data/asset/functions/object/2117.heiloang_tornado/tick/attack.mcfunction
> +
予兆パーティクルと攻撃範囲の乖離は修正しました
浮遊エフェクトについては、フィールド全域に付与するようにしたのでそのままでも問題ありません

2025-01-03 05:29 UTC, mokkkk commented on Asset/data/asset/functions/object/2117.heiloang_tornado/init/.mcfunction
> +# @within asset:object/alias/2117/init
削除しました

2025-01-03 05:29 UTC, mokkkk commented on Asset/data/asset/functions/object/2117.heiloang_tornado/load.mcfunction
> +    # scoreboard objectives add
削除しました

2025-01-03 05:44 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/tornado/.mcfunction
> +
位置と向きのリセット処理を追加しました

2025-01-03 05:46 UTC, mokkkk commented on Asset/data/asset/functions/object/2122.heiloang_flame_vfx/init/.mcfunction
> +# @within asset:object/alias/2122/init
削除しました

2025-01-03 05:47 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/tornado/particle_before.mcfunction
> +
削除しました

2025-01-03 05:47 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/tempest/summon.mcfunction
> +
削除しました

2025-01-03 05:48 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/tempest/particle_before.mcfunction
> +
削除しました

2025-01-03 05:50 UTC, mokkkk commented on Asset/data/asset/functions/object/2121.heiloang_tempest/init/.mcfunction
> +# @within asset:object/alias/2121/init
削除しました

2025-01-03 06:26 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/heil_disaster/attack_wind_burst.mcfunction
> +
削除しました

2025-01-03 06:27 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/heil_disaster/particle_before.mcfunction
> +
削除しました

2025-01-03 06:50 UTC, mokkkk commented on Asset/data/asset/functions/object/2123.heiloang_flare/load.mcfunction
> +    # scoreboard objectives add
削除しました

2025-01-03 06:52 UTC, mokkkk commented on Asset/data/asset/functions/object/2123.heiloang_flare/init/.mcfunction
> +# @within asset:object/alias/2123/init
削除しました

2025-01-03 07:00 UTC, mokkkk commented on Asset/data/asset/functions/object/2123.heiloang_flare/tick/.mcfunction
> +    execute if entity @s[scores={General.Object.Tick=101..}] on passengers run kill @s
円形範囲の消去タイミングの都合
表示側の時間を調整しました

2025-01-03 07:01 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/plamet/move.mcfunction
> +
削除しました

2025-01-03 07:03 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/plamet/set_dive_target.mcfunction
> +
削除しました

2025-01-03 07:05 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/plamet/attack_dive.mcfunction
> +
修正しました

2025-01-03 07:06 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/power_breath/.mcfunction
> +
修正しました

2025-01-03 07:09 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/power_breath_continue_1/end.mcfunction
> +    execute if score @s BE.Pb.Count matches ..1 run tag @s add BE.Skill.PowerBreath.End
アニメーション遷移の都合上です

2025-01-03 07:09 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/power_breath/.mcfunction
> +        execute if score @s BE.EventTimer matches 10..100 at @p[tag=BE.MainTarget] rotated ~ 0 positioned ~ ~0.3 ~ run function asset:mob/0410.heiloang/tick/event/power_breath/particle_attack_area
修正しました

2025-01-03 07:41 UTC, haiiro2gou commented
AJの当たり判定スライムについて
現状のスライムのエンティティデータだと体力1になっているので
データの編集部分をこう変更しておいてほしい
(頭にアイテムを乗せてmodifierを乗せているが、現在体力の変更処理はその前に行われるため体力１のままになっている)
```
data merge entity @s {Silent:1b,NoAI:1b,Size:3,DeathLootTable:"minecraft:empty",Attributes:[{Name:"generic.max_health",Base:1024}]}
```

2025-01-03 07:47 UTC, mokkkk commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/load.mcfunction
> +    # scoreboard objectives add
削除しました

2025-01-03 07:54 UTC, mokkkk commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/tick/.mcfunction
> +
攻撃時の頭から攻撃位置まで伸びるブレス演出の都合上、ほとんど処理が変わらないので現状のままでもいいでしょうか

2025-01-03 07:59 UTC, mokkkk commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/tick/damage_pursuit.mcfunction
> +    tag @a[tag=DXYZ] remove DXYZ
修正しました

2025-01-03 08:03 UTC, mokkkk commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/tick/damage_pursuit.mcfunction
> +        execute if predicate api:global_vars/difficulty/easy run tag @a[tag=DXYZ] remove DXYZ
処理を変えて検知回数を減らしました

2025-01-03 08:05 UTC, mokkkk commented
> AJの当たり判定スライムについて 現状のスライムのエンティティデータだと体力1になっているので データの編集部分をこう変更しておいてほしい (頭にアイテムを乗せてmodifierを乗せているが、現在体力の変更処理はその前に行われるため体力１のままになっている)
> 
> ```
> data merge entity @s {Silent:1b,NoAI:1b,Size:3,DeathLootTable:"minecraft:empty",Attributes:[{Name:"generic.max_health",Base:1024}]}
> ```

対応しました

2025-01-03 08:12 UTC, haiiro2gou requested changes

2025-01-03 08:12 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/init/.mcfunction
> +    execute facing entity @p feet run tp @s ~ ~-0.5 ~ ~ 0
ちぇん氏からストップがかかった
さすがにプレイヤーを向いて 8way はまずい

2025-01-03 08:12 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/init/.mcfunction
> +    execute facing entity @p feet run tp @s ~ ~-0.5 ~ ~ 0
代替案として一つ出されてるのが
ノーマルだと角度0固定
ハードだと前回の攻撃を補完する方向(22.5°ズレ)に出すっていう

2025-01-03 08:13 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/init/locator.mcfunction
> +    scoreboard players operation @s ForwardTargetMobUUID = @e[tag=BE.EntityRoot,limit=1] MobUUID
たしかに
勘違いだった

2025-01-03 08:41 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/init/locator.mcfunction
> +    # effect give @s instant_health infinite 0 true
対応しました

2025-01-03 09:03 UTC, mokkkk commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/init/.mcfunction
> +    execute facing entity @p feet run tp @s ~ ~-0.5 ~ ~ 0
上の通り対応しました

2025-01-03 09:42 UTC, haiiro2gou requested changes

2025-01-03 09:42 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2117.heiloang_tornado/tick/attack.mcfunction
> +
そもそもこれ跳躍エフェクトだし
ここで付けるべきなの？という疑問がある

2025-01-03 09:42 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/power_breath_continue_1/end.mcfunction
> +    execute if score @s BE.Pb.Count matches ..1 run tag @s add BE.Skill.PowerBreath.End
納得した

2025-01-03 09:42 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2128.heiloang_powerbreath/tick/.mcfunction
> +
問題はないと思う

2025-01-03 09:42 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/init/locator.mcfunction
> +    data merge entity @s {Silent:1b,NoAI:1b,DeathLootTable:"minecraft:empty",PersistenceRequired :1b,Attributes:[{Name:"generic.max_health",Base:1024}]}
suggestion にミスがあったので訂正
```suggestion
    data merge entity @s {Silent:1b,NoAI:1b,DeathLootTable:"minecraft:empty",PersistenceRequired :1b,Attributes:[{Name:"generic.max_health",Base:1024d}]}
```

2025-01-03 09:44 UTC, haiiro2gou commented
あと思ったのは
死亡時に何もなかったかのように消えていくのが気になった

2025-01-04 11:47 UTC, mokkkk commented on Asset/data/asset/functions/object/2123.heiloang_flare/tick/prediction_normal.mcfunction
> +    execute positioned ~ ~ ~ run function api:object/summon
自分で確認するのが難しいので報告などあってから対応します

2025-01-05 05:19 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/act/phase_2/reset_element.mcfunction
> +    scoreboard players operation @s BE.Ehd.Thunder -= @s BE.Ehd.Water
修正しました

2025-01-05 05:19 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/act/phase_4/reset_element.mcfunction
> +    scoreboard players operation @s BE.Ehd.Thunder -= @s BE.Ehd.Water
未使用なので削除しました

2025-01-05 05:21 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/act/phase_1/element.m.mcfunction
> +    $execute if score @s BE.Ehd.Thunder matches $(Count) run tag @s add BE.Skill.Blitz
対応しました

2025-01-05 05:33 UTC, mokkkk commented
> 表現があいまいだったので訂正させてもらう
今は7ヶ所に分割して隙間ができるように 4 -> 3 -> 4 の順で攻撃してるわけだけど
3 -> 4 -> 3 のパターンがあってもいいな、という意味だった

対応しました

2025-01-05 05:33 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/init/locator.mcfunction
> +    data merge entity @s {Silent:1b,NoAI:1b,DeathLootTable:"minecraft:empty",PersistenceRequired :1b,Attributes:[{Name:"generic.max_health",Base:1024}]}
修正しました

2025-01-05 05:44 UTC, mokkkk commented
>そもそもこれ跳躍エフェクトだし
ここで付けるべきなの？という疑問がある

設計的な観点なのか、ゲームバランス的な観点の問題なのか分からないので(自分はTSBについてはどちらも疎い)
具体的な解決策というか指針が知りたいです

2025-01-05 05:45 UTC, mokkkk commented
>あと思ったこととして
死亡時に何もなかったかのように消えていくのは少し気になった

登場演出、討伐演出アニメーション作成中です

2025-01-06 16:57 UTC, haiiro2gou commented
> 設計的な観点なのか、ゲームバランス的な観点の問題なのか分からないので(自分はTSBについてはどちらも疎い) 具体的な解決策というか指針が知りたいです

竜巻の命中時なので
恐らく浮遊エフェクトを付けるべきところに跳躍エフェクトが付いてるところを指摘した
コメントも実装とかみ合ってないからその辺も併せて

2025-01-06 17:03 UTC, haiiro2gou commented
それで浮遊エフェクトは
Asset側に送ってるのでEffectAssetにしておくとよい(ID: 125)

2025-01-10 13:38 UTC, mokkkk commented
> それで浮遊エフェクトは
> Asset側に送ってるのでEffectAssetにしておくとよい(ID: 125)

これについては、火炎放射回避ギミックとしての跳躍エフェクトのため間違ってないのでコメントだけ修正します

2025-01-10 15:24 UTC, mokkkk commented
> あと思ったこととして 死亡時に何もなかったかのように消えていくのは少し気になった

暫定的な登場演出と討伐演出を作りました
まだ本気を出してないので退却して、v1.0.0での戦いに備えます

2025-01-10 19:58 UTC, haiiro2gou commented
> これについては、火炎放射回避ギミックとしての跳躍エフェクトのため間違ってないのでコメントだけ修正します

であればヘイルディザスターの実装と同様にヘイローン側のイベント処理に入れてほしかった
これだけ聞いてたのは竜巻の上方向への吹き飛ばしがあるのかもしれないと思っていたため

2025-01-10 20:00 UTC, haiiro2gou requested changes

2025-01-10 20:00 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0410.heiloang/rejoin_process/.mcfunction
> +# @within tag/function asset:rejoin
これたのんだ

2025-01-10 20:01 UTC, haiiro2gou commented
あと linter がエラー吐かないよう修正してね

2025-01-11 09:21 UTC, mokkkk commented on Asset/data/asset/functions/mob/0410.heiloang/tick/event/plamet/attack_plamet.mcfunction
> +    execute at @a[nbt={OnGround:1b},distance=..60] run summon area_effect_cloud ~ ~0.5 ~ {Particle:"block air",Radius:0.5f,Duration:6,Age:4,effects:[{id:"levitation",amplifier:20b,duration:3,show_par
修正しました

2025-01-11 09:24 UTC, mokkkk commented
> であればヘイルディザスターの実装と同様にヘイローン側のイベント処理に入れてほしかった
これだけ聞いてたのは竜巻の上方向への吹き飛ばしがあるのかもしれないと思っていたため

イベント側に移しました

> これたのんだ

使い方あってるか分からないですが対応しました

> あと linter がエラー吐かないよう修正してね

多分対応しました

2025-01-11 14:27 UTC, merged