【Object 2002～2025,2038,2064】ボスウサギのオブジェクト
ProjectTSB/Asset pull request #474
Opened 2024-12-18 13:55 UTC by EllaCoat

ウサギに使用するオブジェクトのみをまとめたものです。

2024-12-18 14:18 UTC, Lapis-LJA requested changes
DamageAPIとDamageLibが混ざってるのでまとめてAPIにしてきて

2024-12-18 14:18 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2004.labyria_thunder/_index.d.mcfunction
未使用

2024-12-18 14:18 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2002.lighting_fast/tick/cast.mcfunction
> +        function lib:damage/reset
DamageLibとDamageAPIが混ざってる

2024-12-18 14:18 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2003.smoke_bomb/tick/cast.mcfunction
> +    function lib:damage/reset
DamageLibとDamageAPIが混ざってる

2024-12-18 14:18 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2003.smoke_bomb/tick/cast.mcfunction
> +    execute as @a[tag=!PlayerShouldInvulnerable,distance=..3] at @s run function api:entity/mob/effect/give
複数人に対してエフェクトが付与できなさそうなので、as @a[] でfunction分けようね

2024-12-18 14:18 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2004.labyria_thunder/init/.mcfunction
> +
$2004.Tempがリセットされてなさそう

2024-12-18 14:25 UTC, EllaCoat commented on Asset/data/asset/functions/object/2002.lighting_fast/tick/cast.mcfunction
> +        function lib:damage/reset
これは別に支障ないと思うよ

2024-12-18 14:25 UTC, quikku commented on Asset/data/asset/functions/object/2002.lighting_fast/tick/cast.mcfunction
> +        function lib:damage/reset
あります
apiにしろ！

2024-12-18 14:26 UTC, EllaCoat commented on Asset/data/asset/functions/object/2002.lighting_fast/tick/cast.mcfunction
> +        function lib:damage/reset
後で一括置換するんでしょ？

2024-12-18 14:26 UTC, quikku commented on Asset/data/asset/functions/object/2002.lighting_fast/tick/cast.mcfunction
> +        function lib:damage/reset
挙動上の問題保証できないとこと（ちぇんちゃ）

2024-12-18 14:27 UTC, EllaCoat commented on Asset/data/asset/functions/object/2002.lighting_fast/tick/cast.mcfunction
> +        function lib:damage/reset
後で一括置換するじゃだめなの？

2024-12-18 14:28 UTC, quikku commented on Asset/data/asset/functions/object/2002.lighting_fast/tick/cast.mcfunction
> +        function lib:damage/reset
直せ

2024-12-18 14:28 UTC, EllaCoat commented on Asset/data/asset/functions/object/2002.lighting_fast/tick/cast.mcfunction
> +        function lib:damage/reset
どう直すか述べよ

2024-12-18 14:29 UTC, quikku commented on Asset/data/asset/functions/object/2002.lighting_fast/tick/cast.mcfunction
> +        function lib:damage/reset
lib: Argument.hogeをapi: Argument.hogeに
lib:damage/hogeをapi:damage/hoge

2024-12-18 14:31 UTC, quikku commented on Asset/data/asset/functions/object/2002.lighting_fast/tick/cast.mcfunction
> +        function lib:damage/reset
ダメージAPI以外のlib: Argumentを巻き込まないように注意ね

2024-12-18 14:38 UTC, quikku commented on Asset/data/asset/functions/object/2022.ecual_critical/tick/cast.mcfunction
> +        execute if predicate api:global_vars/difficulty/min/hard run data modify storage lib: Argument.FixedDamage set value true
apiに

2024-12-29 12:22 UTC, Lapis-LJA requested changes
spectator貫通は、やめようね！絶対、例外ナシで

2024-12-29 12:22 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2012.thunder_spear/init/.mcfunction
> +# @within asset:object/alias/2012/init
未使用？

2024-12-29 12:22 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2012.thunder_spear/tick/elect/hard_cast.mcfunction
> +    execute as @a[gamemode=!creative,distance=..20] run function api:damage/
sp貫通しそう

2024-12-29 12:22 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2012.thunder_spear/tick/elect/normal_cast.mcfunction
> +    execute as @a[gamemode=!creative,distance=..10] run function api:damage/
sp貫通しそう

2024-12-29 12:22 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2014.dimension_sword/tick/cast.mcfunction
> +    execute as @a[gamemode=!creative,distance=..2.5] at @s run function api:damage/
sp貫通

2024-12-29 12:22 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2016.axia_critical/tick/cast.mcfunction
> +    execute as @a[gamemode=!creative,distance=..6] at @s run function api:damage/
sp貫通

2024-12-29 12:22 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2017.ecual_water_magic/init/.mcfunction
> +    execute if score $2017.Temp Temporary matches 0 run return 0
$2017.Tempがリセットされてなさそう

2024-12-29 12:22 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2017.ecual_water_magic/tick/cast.mcfunction
> +    execute as @a[gamemode=!creative,distance=..3.65] at @s run function api:damage/
sp貫通

2024-12-29 12:22 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2022.ecual_critical/init/.mcfunction
> +    execute if score $2022.Temp Temporary matches 0 run return 0
リセットされてなさそう

2025-01-11 02:51 UTC, Lapis-LJA approved these changes
多分いいんじゃないかな

2025-01-11 04:04 UTC, merged