[神器1121]インフェルノラッシュ作成
ProjectTSB/Asset pull request #476
Opened 2024-12-18 14:18 UTC by quikku

2024-12-19 01:20 UTC, quikku commented
タグ消してねぇ

2024-12-19 17:30 UTC, haiiro2gou requested changes

2024-12-19 17:30 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/1121.inferno_rush/trigger/3.main.mcfunction
> +    execute positioned ~ ~1.3 ~ positioned ^ ^ ^1 anchored eyes run function api:object/summon
objectの追尾と一致してない

2024-12-19 17:30 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1075.inferno_rush_arm/tick/.mcfunction
> +    tag @a[tag=1075.Owner] remove 1075.Owner
distanceやlimitで制限したほうが良い

2024-12-19 17:30 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1075.inferno_rush_arm/tick/hit.mcfunction
> +    execute as @e[type=#lib:living,tag=Enemy,distance=..2] run function api:damage/
`Uninterferable` タグを弾くように

2024-12-19 17:30 UTC, haiiro2gou commented on Asset/data/asset/functions/object/1075.inferno_rush_arm/tick/hit.mcfunction
> +    execute facing entity @p[tag=1075.Owner] eyes as @e[type=#lib:living,tag=Enemy,distance=..2] run function lib:motion/
`Uninterferable` タグを弾くように

2024-12-20 19:29 UTC, haiiro2gou approved these changes

2024-12-20 19:45 UTC, merged