【Mob 390～393】ボスウサギ実装
ProjectTSB/Asset pull request #478
Opened 2024-12-18 15:03 UTC by EllaCoat

Objectは別のプルリクに切り出しているので注意

2024-12-19 03:14 UTC, Lapis-LJA requested changes

2024-12-19 03:14 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0390.triple_rabbits/ai/general/break_block.mcfunction
> +    fill ~-15 ~ ~-15 ~15 ~3 ~15 air destroy
if predicate api:area/is_breakable つけよう 今は必要なくても将来的に必要になりうる

2025-01-06 19:39 UTC, Lapis-LJA commented
死亡演出のscheduleをobjectにしてね

2025-01-06 20:23 UTC, Lapis-LJA requested changes

2025-01-06 20:23 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0391.axia_first/ai/animation/7_0_zangekihou/announce_line.mcfunction
> +execute anchored eyes positioned ^ ^ ^2 as @e[tag=AV.AnnounceInit,distance=..0.1] run function asset:mob/0391.axia_first/ai/projectile/announce_line/1.init.m {Num:-25}
typeつけよう

2025-01-06 20:23 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0391.axia_first/ai/animation/7_0_zangekihou/rotate.mcfunction
> +    execute as @e[type=wither_skeleton,tag=this,distance=..64,sort=nearest,limit=1] at @s facing entity @e[tag=AV.Temp.Target,distance=..66,limit=1] feet run tp @s ^ ^ ^ ~ 0
typeつけよう

2025-01-07 00:53 UTC, Chuzume commented on Asset/data/asset/functions/mob/0392.ecual_first/ai/animation/5_0_shining_ray/announce_line.mcfunction
> +execute anchored eyes positioned ^ ^ ^2 as @e[tag=AW.AnnounceInit,distance=..0.1] run function asset:mob/0392.ecual_first/ai/projectile/announce_line/1.init.m {Num:-30}
多分type付けたほうがいいのかも。ウチの方針的に。

2025-01-07 01:04 UTC, Chuzume commented on Asset/data/asset/functions/mob/0392.ecual_first/ai/projectile/announce_line_even/debug.mcfunction
> +execute anchored eyes positioned ^ ^ ^2 as @e[tag=AW.AnnounceInit,distance=..0.1] run function asset:mob/0392.ecual_first/ai/projectile/announce_line_even/1.init.m {Num:-20}
デバッグ用な辺りこうなっている理由もわかるのですが、一応typeつけるべきなのでしょうね…

2025-01-07 01:04 UTC, Chuzume commented on Asset/data/asset/functions/mob/0392.ecual_first/death/.mcfunction
> +    kill @e[tag=AW.AnnounceLineEven]
ディスプレイだと分かりきっているならtypeがあるとよさそうです。あとdistanceもあるといいのかな。

2025-01-07 01:04 UTC, Chuzume commented on Asset/data/asset/functions/mob/0392.ecual_first/ai/animation/5_1_water_bullet/announce_line.mcfunction
> +execute anchored eyes positioned ^ ^ ^2 as @e[tag=AW.AnnounceInit,distance=..0.1] run function asset:mob/0392.ecual_first/ai/projectile/announce_line_even/1.init.m {Num:-30}
type指定があるといいのかな

2025-01-07 01:04 UTC, Chuzume commented on Asset/data/asset/functions/mob/0392.ecual_first/ai/animation/9_0_water_wall/announce.mcfunction
> +execute anchored eyes positioned ^ ^ ^2 as @e[tag=AW.AnnounceInit,distance=..0.1] run function asset:mob/0392.ecual_first/ai/projectile/announce_line/1.init.m {Num:-20}
type指定があるとよさそうです

2025-01-07 01:04 UTC, Chuzume commented on Asset/data/asset/functions/mob/0392.ecual_first/ai/general/2.rotate.mcfunction
> +# 終了
type指定があるとよさそう…と思ったのですが、実行者が向く対象である辺り、もしかしてプレイヤー以外のものに移動することも考慮してます？
ざっと使用箇所を見た感じだと、プレイヤーのほうを向くときにしか使われていないようですが…

2025-01-07 01:20 UTC, Chuzume commented on Asset/data/asset/functions/mob/0393.labyria_first/ai/general/2.rotate.mcfunction
> +# 終了
ラビリアでtypeも必要そうなのはここくらいでした。
ざっと見た感じ、やはりこのコマンドも実行者は基本的にプレイヤーであるようですが、本来は味方モブ的なものに向かう処理とかを想定している？

2025-01-07 01:27 UTC, Chuzume commented on Asset/data/asset/functions/mob/0391.axia_first/ai/animation/10_0_kourai/damage.mcfunction
> +    function lib:damage/reset
ウサギ全員そうなのですが、使用が非推奨とされてる（らしい）libのほうのダメージ処理を使っているようなので、変えたほうがいい…のかな？
該当箇所が多すぎるので、問題がありそうならこちらで修正しますが…

2025-01-07 11:24 UTC, Chuzume commented on Asset/data/asset/functions/mob/0391.axia_first/ai/animation/9_0_dimension_slash/slash_summon.mcfunction
> +    execute positioned ^0 ^1.2 ^1 as @e[tag=2001.CustomEffect,distance=..0.1] facing entity @e[type=wither_skeleton,tag=this,distance=..64,sort=nearest,limit=1] feet rotated ~180 0 run tp @s ^ ^ ^ ~
専用のタグ定義してるのそういうことだったんですね…でもtype指定はあったほうがいいです

2025-01-07 12:43 UTC, Chuzume commented on Asset/data/asset/functions/mob/0391.axia_first/ai/animation/8_0_warp_slash/end.mcfunction
> +    execute if entity @e[tag=AV.SuperiorSkill] run function asset:mob/0391.axia_first/ai/general/7.idle_motion_change
typeがありませんね…足りてないのはここの２つのみでした。

2025-01-07 12:43 UTC, Chuzume commented on Asset/data/asset/functions/mob/0391.axia_first/death/.mcfunction
> +    kill @e[tag=AV.AnnounceLine,distance=..100]
typeがないよ！

2025-01-08 17:19 UTC, EllaCoat commented on Asset/data/asset/functions/mob/0391.axia_first/ai/animation/7_0_zangekihou/rotate.mcfunction
> +    execute as @e[type=wither_skeleton,tag=this,distance=..64,sort=nearest,limit=1] at @s facing entity @e[tag=AV.Temp.Target,distance=..66,limit=1] feet run tp @s ^ ^ ^ ~ 0
これは実行したキャラクターの方を向くという処理のため、typeで限定できない

2025-01-08 17:24 UTC, EllaCoat commented on Asset/data/asset/functions/mob/0392.ecual_first/ai/general/2.rotate.mcfunction
> +# 終了
今のところはプレイヤーにしか使われてないけど、今後別のものに使う用事があるので保留にしたい

2025-01-08 17:26 UTC, EllaCoat commented on Asset/data/asset/functions/mob/0393.labyria_first/ai/general/2.rotate.mcfunction
> +# 終了
別で言った通り、他のモブを対象にする可能性が今後あるので保留で

2025-01-10 12:25 UTC, Lapis-LJA approved these changes
多分いいんじゃないかな

2025-01-11 04:00 UTC, merged