🍱 [Mob106] ミニシュルカーを実装
ProjectTSB/Asset pull request #479
Opened 2024-12-18 17:57 UTC by haiiro2gou

2024-12-19 05:29 UTC, Lapis-LJA requested changes
Mobで飛翔体抽象みたいな実装してるとは思わなかった

2024-12-19 05:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0106.mini_shulker/tick/attack/.mcfunction
> +    execute unless entity @a[tag=2Y.Target,tag=!PlayerShouldInvulnerable,distance=..50,limit=1] run return run function asset:mob/0106.mini_shulker/tick/reset
これ、@pでいいんじゃないかな

2024-12-19 05:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0106.mini_shulker/tick/attack/shoot.mcfunction
> +    execute store result storage api: Argument.FieldOverride.TargetID int 1 run scoreboard players get @a[tag=2Y.Target,distance=..50,limit=1] UserID
質問、sortはnearestとかrandomじゃなくていいの？

2024-12-19 05:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0106.mini_shulker/tick/select/.mcfunction
> +    execute as @a[tag=2Y.Target,distance=..25,limit=1] store result storage asset:context this.TargetID int 1 run scoreboard players get @s UserID
1人をターゲットにするのなら@pでよさそう

2024-12-19 05:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0106.mini_shulker/tick/teleport/.mcfunction
> +    kill @e[type=marker,tag=2Y.Spread,limit=1]
distanceつけた方が軽くなりそうだと思った

2024-12-19 05:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0106.mini_shulker/tick/teleport/secure/start_rec.m.mcfunction
> +    function asset:mob/0106.mini_shulker/tick/teleport/secure/rec.m with storage asset:temp 2Y.Secure
誤字してそう

2024-12-19 05:42 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0106.mini_shulker/tick/attack/.mcfunction
> +    execute unless entity @a[tag=2Y.Target,tag=!PlayerShouldInvulnerable,distance=..50,limit=1] run return run function asset:mob/0106.mini_shulker/tick/reset
挙動が重いので
できるだけ軽くなるように `sort=nearest` (つまり@p)を避けてる

2024-12-19 05:43 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0106.mini_shulker/tick/attack/shoot.mcfunction
> +    execute store result storage api: Argument.FieldOverride.TargetID int 1 run scoreboard players get @a[tag=2Y.Target,distance=..50,limit=1] UserID
攻撃モーションに入った時点でターゲットは指定済み

2024-12-19 05:44 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0106.mini_shulker/tick/attack/.mcfunction
> +    execute unless entity @a[tag=2Y.Target,tag=!PlayerShouldInvulnerable,distance=..50,limit=1] run return run function asset:mob/0106.mini_shulker/tick/reset
@a[]の方が軽いって認識で良い？
@pの方が軽いと思ってたから

2024-12-19 05:44 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0106.mini_shulker/tick/attack/shoot.mcfunction
> +    execute store result storage api: Argument.FieldOverride.TargetID int 1 run scoreboard players get @a[tag=2Y.Target,distance=..50,limit=1] UserID
ならいいか

2024-12-21 02:49 UTC, Lapis-LJA approved these changes
たぶんよさそう

2024-12-26 14:19 UTC, Lapis-LJA approved these changes

2024-12-26 14:24 UTC, merged