♲[Mob237] ルナティックメイジを修正
ProjectTSB/Asset pull request #488
Opened 2024-12-19 14:57 UTC by Lapis-LJA

Fix #403
git mojiに慣れてなくて中途半端になってしまった

2024-12-19 18:27 UTC, haiiro2gou requested changes
- Defense値マイナスっておかしくね？
- 耐性値をもう少しまともにしたほうが良さそう
- スキル選択にバイアス変数を導入すべき
- (どっちでもいいけど)無属性の魔法処理も切り出せばよかったのに…
- (細かいけど) ウォーターマジックの円形予告vfxのファイル名が正しくない

2024-12-19 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/teleport/.mcfunction
>  # 実行座標を中心として-x方向に1、+x方向に1、-y方向に0.2、+y方向に0.8、-z方向に1、+z方向に1の立方体内のランダムな位置にmarkerを移動
コメントが嘘すぎる

2024-12-19 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/magic_summon/fire.mcfunction
> +
objectのinitでやるべき

2024-12-19 18:27 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/magic_summon/fire.mcfunction
> +    execute store result storage api: Argument.FieldOverride.MobUUID int 1 run scoreboard players get @e[type=zombie,tag=this,distance=..3,limit=1] MobUUID
実行者がルナメ本体のはずでは

2024-12-20 01:53 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/magic_summon/fire.mcfunction
> +    execute store result storage api: Argument.FieldOverride.MobUUID int 1 run scoreboard players get @e[type=zombie,tag=this,distance=..3,limit=1] MobUUID
summon markerしてるよ

2024-12-20 01:57 UTC, Lapis-LJA commented
ウォーターマジックのファイル名が正しくないはこのPRで対処することではない気がするな

2024-12-20 04:16 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/magic_summon/fire.mcfunction
> +    execute store result storage api: Argument.FieldOverride.MobUUID int 1 run scoreboard players get @e[type=zombie,tag=this,distance=..3,limit=1] MobUUID
仮にそうだとしても
そもそもルナメはハスクでは？

2024-12-20 04:18 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0237.lunatic_mage/tick/skill/magic_summon/fire.mcfunction
> +    execute store result storage api: Argument.FieldOverride.MobUUID int 1 run scoreboard players get @e[type=zombie,tag=this,distance=..3,limit=1] MobUUID
中身をゾンビに変えることで解決

2024-12-21 05:56 UTC, haiiro2gou approved these changes
よさそう

2024-12-21 05:56 UTC, merged