✨ [神器606] 交通標識を作成
ProjectTSB/Asset pull request #49
Opened 2024-01-08 12:33 UTC by EllaCoat

殴ることのできる交通標識

2024-01-08 17:07 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0606.traffic_sign/trigger/5.damage.mcfunction
> +    execute store result storage lib: Argument.Damage float 0.5 run scoreboard players operation $GU.Temp Temporary > $1 Const
これってダメージ2桁台になるってこと？

2024-01-08 17:08 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0606.traffic_sign/trigger/5.damage.mcfunction
> +    execute store result storage lib: Argument.Damage float 0.5 run scoreboard players operation $GU.Temp Temporary > $1 Const
ならダメージ計算の注釈は変えてほしい

2024-01-08 17:11 UTC, haiiro2gou requested changes

2024-01-08 17:11 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0606.traffic_sign/trigger/3.main.mcfunction
> +    execute store result storage lib: Argument.Damage float 1 run scoreboard players add $GU.Temp Temporary 200
200-399ダメっぽいので$201をTemporaryで定義付けしたほうがいいかも

2024-01-09 02:13 UTC, EllaCoat commented on Asset/data/asset/functions/artifact/0606.traffic_sign/trigger/3.main.mcfunction
> +    execute store result storage lib: Argument.Damage float 1 run scoreboard players add $GU.Temp Temporary 200
面倒だから201〜400にしておくわ

2024-01-09 02:24 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0606.traffic_sign/trigger/5.damage.mcfunction
> +    execute store result storage lib: Argument.Damage float 0.5 run scoreboard players operation $GU.Temp Temporary > $1 Const
多分×50かな？

2024-01-09 02:24 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0606.traffic_sign/trigger/3.main.mcfunction
> +    execute store result storage lib: Argument.Damage float 1 run scoreboard players add $GU.Temp Temporary 200
お願いするわ

2024-02-01 16:45 UTC, haiiro2gou approved these changes
よさげ

2024-04-28 07:16 UTC, merged