ブレイジング・インフェルノとそのしたっぱを作成
ProjectTSB/Asset pull request #497
Opened 2024-12-20 22:44 UTC by Chuzume

- ボス本体の攻撃力が一部未調整です。多分一部の技は痛すぎるし、一部の技はカスみたいなダメージです。
- 下っ端は本当にただのブレイズなので、レビューはすぐ終わるはずです。ステータスも調整済み。
- ハードだと動作が強化されるタイプです。
- 一部演出がラスボスと一緒（っていうか流用してる）ので派手過ぎるかもしれない。でもパーティクル数が減らせるし…

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/skill_select/.mcfunction
> +    #declare score_holder $Random
ん、これいる？使ってる場所ないぞ

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/rush_punch/punch/.mcfunction
> +    function asset:mob/0311.blazing_inferno/tick/skill/rush_punch/punch/break_block
一応なんだけど将来的にアリーナとか作るかもしれんからアドベでも動くように
if predicate api:area/is_breakableをつけるべきかも

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/dash_punch/explosion.mcfunction
> +    execute positioned ^ ^-1 ^1 run function asset:mob/0311.blazing_inferno/tick/skill/dash_punch/break_block
アドベでも大丈夫なようにif predicate api:area/is_breakableを

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/summon_minion/banish_minion.mcfunction
> +    function api:mob/kill
まあ対して変わらんけどapi:mob/removeでもいいかもね

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/summon_minion/spread.mcfunction
> +    execute as @e[type=marker,tag=SpreadMarker,distance=..64,limit=1] at @e[type=marker,tag=8N.Marker.SpawnPoint,limit=1] run function lib:spread_entity/
atのほうdistance抜けてる
つけたほうがいいかも

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/object/2135.blazing_fireball/kill/.mcfunction
> +    tag @a[tag=Hit] remove Hit
distance

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/object/2136.blazing_bomb/kill/.mcfunction
> +    tag @a[tag=Hit] remove Hit
distance

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/object/2136.blazing_bomb/kill/place_aoe.mcfunction
> +    fill ~3 ~ ~3 ~-3 ~ ~-3 fire[age=5] replace air
アドベでも大丈夫なようにif predicate api:area/is_breakable

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/object/2137.blazing_aoe/tick/.mcfunction
> +    scoreboard players operation $Interval Temporary = @s General.Object.Tick
declare

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/object/2148.blazing_inferno_dead/tick/.mcfunction
> +    scoreboard players operation $Interval Temporary = @s General.Object.Tick
declare

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/mob/0311.blazing_inferno/death/.mcfunction
> +    execute facing entity @p eyes run function api:object/summon
@pにもdistanceいるかも
該当箇所多いから一括置換で

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/object/2136.blazing_bomb/kill/.mcfunction
> +    execute as @a[tag=Hit,tag=!PlayerShouldInvulnerable] run function api:damage/
distance

2024-12-20 23:21 UTC, quikku commented on Asset/data/asset/functions/object/2147.blazing_slam_laser/tick/thunder.mcfunction
> +    tag @a[tag=Hit] remove Hit
distance

2024-12-21 00:23 UTC, Chuzume commented on Asset/data/asset/functions/mob/0311.blazing_inferno/death/.mcfunction
> +    execute facing entity @p eyes run function api:object/summon
ここに限って言えば、迷ったんですがこれが実行されないと困るので絶対実行されるようにしています
…いやまぁ、死亡時の演出だから最悪召喚されなくても構わないのか？

2024-12-21 00:23 UTC, quikku commented on Asset/data/asset/functions/mob/0311.blazing_inferno/death/.mcfunction
> +    execute facing entity @p eyes run function api:object/summon
まあそれ以外の場所だとディメンション跨いだりしてめんどいかもだから場所みて治してちょ

2024-12-21 01:49 UTC, Lapis-LJA requested changes

2024-12-21 01:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0311.blazing_inferno/_index.d.mcfunction
空の行があるとtagの定義が全体に及んじゃうから、何も書いてない行にも #つけよう

2024-12-21 01:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/skill_select/.mcfunction
> +    scoreboard players set @s General.Mob.Tick -10
コメントとコマンドがあってなさそう

2024-12-21 01:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/dash_punch/move_stacked.mcfunction
> +    summon falling_block ~ ~ ~ {BlockState:{Name:"minecraft:fire",Properties:{age:"5"}},Time:1,DropItem:0b,HurtEntities:0b,Motion:[0.0,0.3,0.0]}
if predicate api:area/is_breakable つけよう

2024-12-21 01:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/firebomb/shoot.mcfunction
> +#declare tag SpreadMarker
これSpreadMarker使ってる？

2024-12-21 01:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/firebomb/spread_ball.mcfunction
> +    execute as @e[type=marker,tag=SpreadMarker,limit=1] run function lib:forward_spreader/circle
一応distanceだけつけとこう

2024-12-21 01:49 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/firebomb/throw_spread.mcfunction
> +    function api:mob/summon
ID:314なMobっていたっけ...?

2024-12-21 02:47 UTC, Lapis-LJA requested changes

2024-12-21 02:47 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2136.blazing_bomb/kill/place_aoe.mcfunction
> +    function api:object/summon
MobUUIDを2回設定してる？

2024-12-21 02:47 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2147.blazing_slam_laser/tick/thunder.mcfunction
> +
hostileとneutralが混ざってるのは意図的？

2024-12-21 02:47 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/passive_laser/summon.mcfunction
> +        kill @e[type=marker,tag=SpreadMarker,limit=1]
distanceがあったほうが良いかも？

2024-12-21 02:47 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/skill_select/.mcfunction
> +# 属性に応じたスキルを選択する
細かいけど、属性？

2024-12-21 19:17 UTC, Chuzume commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/skill_select/.mcfunction
> +    scoreboard players set @s General.Mob.Tick -10
「こまけ～」とも思いましたが、まぁ確かに…よくないな。

2024-12-21 19:18 UTC, Chuzume commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/skill_select/.mcfunction
> +# 属性に応じたスキルを選択する
…トゥルから流用したからですね。直しておきます。

2024-12-21 19:32 UTC, Chuzume commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/passive_laser/.mcfunction
> +    scoreboard players operation $Interval Temporary = @s 8N.PassiveLaser
…なんのリセット？

2024-12-21 19:37 UTC, Chuzume commented on Asset/data/asset/functions/mob/0311.blazing_inferno/summon/.mcfunction
> +summon wither_skeleton ~ ~ ~ {NoAI:1b,Silent:1b,Tags:["MobInit","AlwaysInvisible","8N.Moveset.Intro"],DeathLootTable:"minecraft:empty",DeathTime:19s}
ヘトゥとかを倒してみましたが普通に倒れる演出が入ったので強制19ではないようです。

2024-12-22 05:26 UTC, quikku commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/base_move/passive_laser/.mcfunction
> +    scoreboard players operation $Interval Temporary = @s 8N.PassiveLaser
スコアホルダーのリセットね
修正してるみたいだから良し
リセットは必須なのです

2024-12-22 19:34 UTC, Chuzume commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/summon_minion/spread.mcfunction
> +    execute as @e[type=marker,tag=SpreadMarker,distance=..64,limit=1] at @e[type=marker,tag=8N.Marker.SpawnPoint,limit=1] run function lib:spread_entity/
…ここ以外にもついてないとこあるけど必要なんですか？limitは付いてますよ

2024-12-22 19:46 UTC, quikku commented on Asset/data/asset/functions/mob/0311.blazing_inferno/tick/skill/summon_minion/spread.mcfunction
> +    execute as @e[type=marker,tag=SpreadMarker,distance=..64,limit=1] at @e[type=marker,tag=8N.Marker.SpawnPoint,limit=1] run function lib:spread_entity/
distanceは負荷軽減になるらしい（よくわからんしつけとけ精神ではある）

2024-12-25 03:20 UTC, Lapis-LJA approved these changes
たぶんよさそう

2024-12-26 12:16 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0311.blazing_inferno/death/.mcfunction
> +    kill @e[type=blaze,scores={MobID=313},distance=..64]
Mobをキルしてはいけない！
```suggestion
# 付近のしもべをキル
    execute as @e[type=blaze,scores={MobID=313},distance=..64] run api:mob/kill
```

2024-12-26 12:17 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0311.blazing_inferno/remove/.mcfunction
> +
remove時にしもべを削除しておいたほうが良さそう
```suggestion

# 付近のしもべを削除
    execute as @e[type=blaze,scores={MobID=313},distance=..64] run function api:mob/remove

```

2024-12-26 12:20 UTC, haiiro2gou requested changes
すまんな、これだけやっといてくれ

2024-12-26 20:22 UTC, Chuzume commented
色々見落としていました（特にモブのキル、画面外で死ぬとはいえなにかか良くないことが起きそう）サジェスト置いておいてくれてありがとうね！

2024-12-27 00:37 UTC, haiiro2gou approved these changes
よさそう

2024-12-27 00:38 UTC, merged