全体定義になっていたtagとscore_holderを修正
ProjectTSB/Asset pull request #498
Opened 2024-12-21 02:07 UTC by Lapis-LJA

気になってしまった

2025-01-11 09:08 UTC, haiiro2gou requested changes

2025-01-11 09:08 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0787.aurora_helm/trigger/_index.d.mcfunction
> +#> private
?

2025-01-11 09:09 UTC, haiiro2gou commented
CBTに合わせて入れるぞ

2025-01-11 09:19 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/0787.aurora_helm/trigger/_index.d.mcfunction
> +#> private
原因がわかんなかったんや...

2025-01-11 14:09 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0787.aurora_helm/trigger/_index.d.mcfunction
> +#> private
こっちで直すぞ

2025-02-02 08:48 UTC, haiiro2gou commented
キャッシュを再生成すべし

2025-05-10 16:02 UTC, ChenCMD commented
@Lapis-LJA この PR どうする？

2025-05-11 02:34 UTC, Lapis-LJA commented
conflictやばいしだいぶ古いし一度なかったことにするか

2025-05-11 02:34 UTC, closed without merging