【Mob380】ハルクレアV3作成
ProjectTSB/Asset pull request #501
Opened 2024-12-22 09:46 UTC by mokkkk

一旦完成したのでプルリクエストを作成。
演出が簡略かつ簡単すぎる攻撃があるので、レビュー中に修正する可能性がある。

対象
- Mob
  - 380
- Object
  - 2149
  - 2150
  - 2151
  - 2152
  - 2153
  - 2154
  - 2155

2024-12-25 09:45 UTC, Lapis-LJA requested changes

2024-12-25 09:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2149.haruclaire_icebullet/hit_entity/.mcfunction
> +    data modify storage api: Argument.FixedDamage set value 1b
他のObjectにもFixedDamageついてるけど、これ固定ダメージになるけど意図的？

2024-12-25 09:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2150.haruclaire_ice_wall/load.mcfunction
> +    # scoreboard objectives add
未使用っぽい

2024-12-25 09:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2151.haruclaire_icewall_center/init/.mcfunction
> +# @within asset:object/alias/2151/init
未使用っぽい

2024-12-25 09:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2151.haruclaire_icewall_center/load.mcfunction
> +    # scoreboard objectives add
未使用っぽい

2024-12-25 09:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2153.haruclaire_thrown_rod/tick/spin.mcfunction
> +    execute if entity @s[tag=2153.Inverse,scores={2153.Sub=4..}] run data modify entity @s transformation set value [0.5655f,-0.4994f,0.6564f,0.0000f,0.4543f,0.8528f,0.2574f,0.0000f,-0.6884f,0.1526f,
2153.Subをloadで生成してなさそう？

2024-12-25 09:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2154.haruclaire_super_icebullet/hit_block/.mcfunction
> +
hit_entityにもhit_blockにも同じ処理を書くならkillメソッド用意したら一つにまとめられてすっきりするかも？

2024-12-25 09:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2154.haruclaire_super_icebullet/load.mcfunction
> +    # scoreboard objectives add
未使用っぽい

2024-12-25 09:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2155.haruclaire_icelaser/init/.mcfunction
> +# @within asset:object/alias/2155/init
未使用っぽい？

2024-12-25 09:45 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2155.haruclaire_icelaser/tick/attack.mcfunction
> +
必須じゃないんだけど気になったので

```suggestion
#> Private
# @private
    #declare score_holder $Interval
```

2024-12-25 10:12 UTC, Lapis-LJA reviewed
単純に疑問として、プレイヤーにタグ付けてターゲティングする実装だとプレイヤーが抜けた時って大丈夫なのかな？

2024-12-25 13:24 UTC, mokkkk commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/_index.d.mcfunction
> +    #declare tag AK.Temp.AttackRotation 攻撃角度保持用
修正しました

2024-12-25 13:25 UTC, mokkkk commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/rejoin_process/.mcfunction
> +# @within tag/function asset:rejoin
削除しました

2024-12-25 13:27 UTC, mokkkk commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/act/phase_1/punch.mcfunction
> +    execute if entity @a[distance=..4] run return run tag @s add AK.Skill.Punch
変えました
ついでにつらら（アイススピア）のターゲットも同様に修正

2024-12-25 13:30 UTC, mokkkk commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/act/.mcfunction
> +    execute as @e[type=item_display,tag=AK.ModelRoot,sort=nearest,limit=1] unless entity @s[tag=aj.haruclaire_aj.animation.1_0_rod_idle.playing] run function asset:mob/0380.haruclaire_v3/tick/animate
定義しました

2024-12-25 13:32 UTC, mokkkk commented on Asset/data/asset/functions/object/2150.haruclaire_ice_wall/load.mcfunction
> +    # scoreboard objectives add
演出や仕様変更の際に追加しなおす手間を減らしたいので、正式版完成まで残しておきたいです
以下同様の指摘に対しても同じ回答

2024-12-25 13:32 UTC, Lapis-LJA commented on Asset/data/asset/functions/object/2150.haruclaire_ice_wall/load.mcfunction
> +    # scoreboard objectives add
ok

2024-12-25 13:35 UTC, mokkkk commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/util/move_to_ground_loop.mcfunction
> +# @within asset:mob/0380.haruclaire_v3/tick/util/move_to_ground_loop
今後実装/修正するうえで気づいた部分は直すけど一括で探して直すのが手間かかりそうなので勘弁

2024-12-25 13:36 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/util/move_to_ground_loop.mcfunction
> +# @within asset:mob/0380.haruclaire_v3/tick/util/move_to_ground_loop
おｋ

2024-12-25 13:39 UTC, mokkkk commented on Asset/data/asset/functions/object/2155.haruclaire_icelaser/tick/attack.mcfunction
> +
対応しました

2024-12-25 13:39 UTC, mokkkk commented on Asset/data/asset/functions/object/2153.haruclaire_thrown_rod/tick/spin.mcfunction
> +    execute if entity @s[tag=2153.Inverse,scores={2153.Sub=4..}] run data modify entity @s transformation set value [0.5655f,-0.4994f,0.6564f,0.0000f,0.4543f,0.8528f,0.2574f,0.0000f,-0.6884f,0.1526f,
なぜか消えてたっぽいので再度追加しました

2024-12-25 13:40 UTC, mokkkk commented on Asset/data/asset/functions/object/2149.haruclaire_icebullet/hit_entity/.mcfunction
> +    data modify storage api: Argument.FixedDamage set value 1b
コピペ時のミスのようなので消しました

2024-12-25 13:49 UTC, mokkkk commented on Asset/data/asset/functions/object/2154.haruclaire_super_icebullet/hit_block/.mcfunction
> +
killを追加して、hit_xxxは削除しました（通常のアイスバレットも同様）

2024-12-25 13:51 UTC, mokkkk commented
> 単純に疑問として、プレイヤーにタグ付けてターゲティングする実装だとプレイヤーが抜けた時って大丈夫なのかな？

ターゲットがいない場合、近くの別プレイヤーに狙いを変える処理を書きました
プレイヤー退出や神器などによる帰還に対応できると思う

2024-12-25 14:26 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/tick/act/.mcfunction
> +    return 0
ここデバッグ用だけどコメントアウトされてないのは大丈夫？

2024-12-25 16:29 UTC, Lapis-LJA requested changes

2024-12-25 16:29 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/_index.d.mcfunction
> +    # - 汎用
これでエラー消えるかも？
他にスコアを増やしたのなら随時追加する感じ

```suggestion
    #declare tag
    #
    # - AJ自動生成スコア
    #declare objective aj.0_0_start.frame
    #declare objective aj.1_0_rod_idle.frame
    #declare objective aj.3_0_rod_move.frame
    #declare objective aj.4_0_rod_icewall.frame
    #declare objective aj.5_0_rod_icebullet.frame
    #declare objective aj.6_1_rod_super_icebullet.frame
    #declare objective aj.8_0_rod_punch.frame
    #declare objective aj.9_0_rod_laser.frame
    #
    # - 汎用
```

2024-12-25 17:02 UTC, mokkkk commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/_index.d.mcfunction
> +    # - 汎用
やりました

2024-12-26 04:15 UTC, Lapis-LJA approved these changes
多分よさそう

2024-12-26 13:50 UTC, haiiro2gou requested changes
death と remove でスキル用の object を削除したほうが良さそう
object なら kill コマンドで問題ないのでやってもらえると嬉しい

2024-12-26 13:50 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/hurt/.mcfunction
> +    function asset:mob/super.hurt
継承元の処理しかしないならファイルごと要らない気がする

2024-12-26 14:14 UTC, Lapis-LJA commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/hurt/.mcfunction
> +    function asset:mob/super.hurt
今後演出とか追加する可能性があるんでしょ

2024-12-26 14:17 UTC, mokkkk commented on Asset/data/asset/functions/mob/0380.haruclaire_v3/hurt/.mcfunction
> +    function asset:mob/super.hurt
現時点でも被ダメージ時の効果音くらい付けときます

2024-12-28 12:12 UTC, mokkkk commented
> death と remove でスキル用の object を削除したほうが良さそう object なら kill コマンドで問題ないのでやってもらえると嬉しい

対応しました

2024-12-28 12:37 UTC, haiiro2gou approved these changes

2024-12-28 12:38 UTC, merged