[モブID372]ツタンカーメンを作成
ProjectTSB/Asset pull request #505
Opened 2024-12-27 08:32 UTC by Chuzume

やけにビュンビュン飛び回りながらレーザーを撃ったり、棺を置いたりしてきます。
瑠璃氏から引き継いだものなので、書き方が混ざっており読みづらい可能性があります。場合によっては全箇所書き換えるのも視野に入っているヨ

2024-12-29 20:24 UTC, Chuzume commented
存在する音を使っているのにLinterが通っていません。結局これ、どうすればいいんですか？
新しい音を使えというならそうしますが、できるだけ避けたいです。

2024-12-30 17:00 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/laser/alert.mcfunction
> +    execute if entity @s[distance=..32] positioned ^ ^ ^1 run function asset:mob/0372.tutankhamen/tick/skill/laser/alert
壁があっても再帰しそう

2024-12-30 17:04 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/dash/side/.mcfunction
> +
挙動として処理されてない気がする

2024-12-30 17:11 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/many_shoot/summon.mcfunction
> +
嘘コメ

2024-12-30 17:18 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2168.general_long_laser/tick/transform.mcfunction
> +    data modify entity @s transformation.scale[1] set from storage asset:context this.Length
未使用ファイル

2024-12-30 17:19 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2168.general_long_laser/tick/.mcfunction
> +
後ろに半分はみ出てる

2024-12-30 17:21 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2090.magic_square/init/.mcfunction
> +# @within asset:object/alias/2090/init
未使用

2024-12-30 17:21 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2090.magic_square/_index.d.mcfunction
> +    #declare
未使用

2024-12-30 17:28 UTC, haiiro2gou commented
音はoggにブリーズの音を追加する形で対策するといいんじゃないかな
ソース: [ここ](https://discord.com/channels/742465492861845564/821965706715332618/1323149363433836648)

2024-12-30 19:24 UTC, Chuzume commented on Asset/data/asset/functions/object/2168.general_long_laser/tick/.mcfunction
> +
どういう意味ですか？

2024-12-30 19:36 UTC, Chuzume commented on Asset/data/asset/functions/object/2168.general_long_laser/tick/.mcfunction
> +
あ～、これもしかしたらリソースパックが原因かもしれません。それを直したやつをプッシュしそこねていました。今見たら治ってませんか？

2024-12-30 19:48 UTC, Chuzume commented on Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/dash/side/.mcfunction
> +
「挙動として処理される」というのはどういう意味ですか？
確認してみましたが、ノーマルハードともにダッシュをキャンセルしてもう一度ダッシュしてきました

2024-12-31 05:59 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/laser/windup.mcfunction
> +    execute as @r[distance=..32] run function lib:get_name/
今気づいたけどこれスペクテイターもターゲットするね

2024-12-31 05:59 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2092.ghost_bullet/init/.mcfunction
> +
フィールド内で戦闘することを考えるとこんなに Range いらないかも

2024-12-31 05:59 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2168.general_long_laser/tick/.mcfunction
> +
直ってた
さんきゅー

2024-12-31 06:56 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2093.tutankhamen_death/tick/end.mcfunction
> +
アンクがないぜ！

2024-12-31 06:56 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/dash/side/.mcfunction
> +
動いてたわ、勘違いだったみたい

2024-12-31 06:57 UTC, haiiro2gou requested changes
上の通り

2025-01-01 08:09 UTC, Chuzume commented on Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/laser/windup.mcfunction
> +    execute as @r[distance=..32] run function lib:get_name/
これ、瑠璃くんがそうしてたので意図的なものだと判断したんですが、どうなんでしょう…（霊界トランスとかを狙うのを想定している？）

2025-01-01 08:09 UTC, Chuzume commented on Asset/data/asset/functions/object/2092.ghost_bullet/init/.mcfunction
> +
これもまぁ瑠璃くんがやってたとはいえ、まぁ確かに遠くに飛んできすぎですねコレ…

2025-01-01 08:28 UTC, Chuzume commented on Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/laser/windup.mcfunction
> +    execute as @r[distance=..32] run function lib:get_name/
追記: クリエイティブはデバッグとかの都合で撃たせたいらしいので、スペクテイターを除外して対応しました

2025-01-02 01:00 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0372.tutankhamen/tick/skill/laser/windup.mcfunction
> +    execute as @r[distance=..32] run function lib:get_name/
ボス戦中に倒されたプレイヤーがスペクテイターで待機することと、戦闘中に霊界トランスが使用できないことからたぶん忘れてただけかな

2025-01-02 01:02 UTC, haiiro2gou approved these changes

2025-01-02 01:06 UTC, merged