【Mob420】アストロブレイズ実装
ProjectTSB/Asset pull request #508
Opened 2024-12-27 21:37 UTC by EllaCoat

大量の弾幕を撃ってくるブレイズ。
弾幕を撃ってくる前にしっかりと合図がある。

2024-12-29 08:15 UTC, haiiro2gou approved these changes
キレイに突進してくるのだけ確認したらマージする

2024-12-29 09:53 UTC, haiiro2gou requested changes

2024-12-29 09:53 UTC, haiiro2gou commented on Asset/data/asset/functions/object/2171.astro_blaze_bullet/register.mcfunction
> +    data modify storage asset:object Field set value {Speed:4,Range:256,MovePerStep:0.15}
1体だけでも 50ms/t 割るほどに重いぜ！
```suggestion
# フィールド(オプション)
    data modify storage asset:object Field set value {Speed:2,Range:128,MovePerStep:0.3}
```

2024-12-29 10:46 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0420.astro_blaze/summon/.mcfunction
> +    summon blaze ~ ~ ~ {Tags:["MobInit","AntiBurn","AlwaysSlowFall"],Passengers:[{id:"minecraft:block_display",Tags:["AllowProcessingCommonTag","AutoKillWhenDieVehicle"],teleport_duration:1,brightnes
結局燃えてるし火も吹くぜ！

2025-01-06 01:28 UTC, EllaCoat commented on Asset/data/asset/functions/object/2171.astro_blaze_bullet/register.mcfunction
> +    data modify storage asset:object Field set value {Speed:4,Range:256,MovePerStep:0.15}
軽くしてみた、他も直すかも

2025-01-06 01:28 UTC, EllaCoat commented on Asset/data/asset/functions/mob/0420.astro_blaze/summon/.mcfunction
> +    summon blaze ~ ~ ~ {Tags:["MobInit","AntiBurn","AlwaysSlowFall"],Passengers:[{id:"minecraft:block_display",Tags:["AllowProcessingCommonTag","AutoKillWhenDieVehicle"],teleport_duration:1,brightnes
たしかに、修正した

2025-01-06 12:00 UTC, haiiro2gou approved these changes

2025-01-06 12:00 UTC, merged