【Mob421～422】シミシミタレット実装
ProjectTSB/Asset pull request #509
Opened 2024-12-27 22:54 UTC by EllaCoat

シルバーフィッシュ（シミシミバレット）を発射するタレットをかついだシルバーフィッシュです。

2024-12-29 08:20 UTC, haiiro2gou requested changes

2024-12-29 08:20 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0421.silver_turret/attack/.mcfunction
> +        data modify storage lib: Argument.DeathMessage append value '[{"translate": "%1$sは%2$sに群がれて倒れてしまった","with":[{"selector":"@s"},{"nbt":"Return.AttackerName","storage":"lib:","interpret":true}]}
多分「群がられて」だと思う
が、自分でも自信がない

2024-12-29 08:20 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0421.silver_turret/tick/.mcfunction
> +    execute if score @s General.Mob.Tick matches 150.. if score @s BP.SummonCount matches 20.. run scoreboard players set @s General.Mob.Tick 0
これ召喚数が一定以上だったら
tick 加算前に return でいいんじゃ？

2024-12-29 08:20 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0422.silver_bullet/attack/.mcfunction
> +        data modify storage lib: Argument.DeathMessage append value '[{"translate": "%1$sは%2$sに群がれて倒れてしまった","with":[{"selector":"@s"},{"nbt":"Return.AttackerName","storage":"lib:","interpret":true}]}
同様

2024-12-29 08:52 UTC, EllaCoat commented on Asset/data/asset/functions/mob/0421.silver_turret/tick/.mcfunction
> +    execute if score @s General.Mob.Tick matches 150.. if score @s BP.SummonCount matches 20.. run scoreboard players set @s General.Mob.Tick 0
たしかにー

2025-01-06 01:28 UTC, EllaCoat commented on Asset/data/asset/functions/mob/0421.silver_turret/attack/.mcfunction
> +        data modify storage lib: Argument.DeathMessage append value '[{"translate": "%1$sは%2$sに群がれて倒れてしまった","with":[{"selector":"@s"},{"nbt":"Return.AttackerName","storage":"lib:","interpret":true}]}
修正した

2025-01-06 01:28 UTC, EllaCoat commented on Asset/data/asset/functions/mob/0422.silver_bullet/attack/.mcfunction
> +        data modify storage lib: Argument.DeathMessage append value '[{"translate": "%1$sは%2$sに群がれて倒れてしまった","with":[{"selector":"@s"},{"nbt":"Return.AttackerName","storage":"lib:","interpret":true}]}
修正した

2025-01-06 01:28 UTC, EllaCoat commented on Asset/data/asset/functions/mob/0421.silver_turret/tick/.mcfunction
> +    execute if score @s General.Mob.Tick matches 150.. if score @s BP.SummonCount matches 20.. run scoreboard players set @s General.Mob.Tick 0
修正した

2025-01-06 11:58 UTC, haiiro2gou approved these changes

2025-01-06 16:37 UTC, merged