[神器769-770] シェイキングスプラッシュの作成
ProjectTSB/Asset pull request #57
Opened 2024-01-16 10:22 UTC by Lapis-LJA

TheSkyBlessingリポジトリから移動

2024-04-28 07:15 UTC, haiiro2gou requested changes
`DisableBreakSound`を有効化したほうがいい説

2024-04-28 07:15 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0769.shaking_splash/trigger/bullet/main.mcfunction
> +    execute if entity @s[scores={LD.Tick=80..}] run kill @e[type=snowball,tag=LD.Bullet,distance=..0.01,sort=nearest,limit=1]
```suggestion
    execute if entity @s[scores={LD.Tick=80..}] positioned ~ ~-0.25 ~ run kill @e[type=snowball,tag=LD.Bullet,distance=..0.01,sort=nearest,limit=1]
```
キルされてねえ

2024-04-28 07:20 UTC, haiiro2gou commented
あとまだ音が小さい気がする

2024-04-29 09:38 UTC, Lapis-LJA commented
そんな音小さいかな？

2024-04-30 14:01 UTC, haiiro2gou commented
小さくないらしい…？

2024-04-30 14:02 UTC, haiiro2gou approved these changes

2024-04-30 14:02 UTC, merged