[Mob330]: オーロラリーパーを作成
ProjectTSB/Asset pull request #6
Opened 2023-11-21 14:09 UTC by Lapis-LJA

2023-11-21 15:18 UTC, Lapis-LJA commented
デスログ考える必要アリ

2024-04-15 09:24 UTC, haiiro2gou requested changes

2024-04-15 09:24 UTC, haiiro2gou commented on Asset/data/asset/functions/mob/0330.aurora_reaper/summon/2.summon.mcfunction
> +    data modify storage asset:mob Name set value '[{"text":"オ","color":"#00FFE2"},{"text":"ー","color":"##00f0e5"},{"text":"ロ","color":"#00e1e9"},{"text":"ラ","color":"#00d3ec"},{"text":"リ","color":"#0
カラーコードが一つだけ##になってるので直してね

2024-04-16 13:43 UTC, haiiro2gou approved these changes
いいんじゃね？

2024-04-16 13:43 UTC, merged