[神器758-759] Sina-TKを作成
ProjectTSB/Asset pull request #68
Opened 2024-01-17 08:48 UTC by Lapis-LJA

2024-04-28 17:13 UTC, haiiro2gou requested changes

2024-04-28 17:13 UTC, haiiro2gou commented on Asset/data/asset/functions/artifact/0759.sina_tk_empty/trigger/2.check_condition.mcfunction
> +    execute if score $Count Temporary matches ..15 run function lib:message/artifact/dont_have_require_items
竹が足りないと鬼のようにうるさいので何とかしてほしいかも？

2024-04-28 17:15 UTC, Lapis-LJA commented on Asset/data/asset/functions/artifact/0759.sina_tk_empty/trigger/2.check_condition.mcfunction
> +    execute if score $Count Temporary matches ..15 run function lib:message/artifact/dont_have_require_items
対策が思いつかない

2024-04-28 17:18 UTC, haiiro2gou commented
スコアを用意するくらいしか

2024-04-29 07:36 UTC, Lapis-LJA commented
ちょっと考えてみたけど、ホットバー神器みたいにオート発動な訳でもないし要らないのではという結論になった

2024-04-29 17:56 UTC, haiiro2gou commented
スニークキープが発動条件だから毎秒20回表示されるんよ

2024-04-29 18:08 UTC, quikku commented
いっそlib:message側で対処するのもいいんじゃない？
他の神器にも似たような処理いれるのもかったるいっしょ

2024-04-29 18:31 UTC, haiiro2gou approved these changes
確かにそうかも

2024-04-29 18:38 UTC, merged