✨ [神器775&778] 翡翠装備の頭と足部位を作成
ProjectTSB/Asset pull request #72
Opened 2024-01-23 09:10 UTC by Lapis-LJA

同じ装備なのにfunction tagでの位置が違うのが嫌だったので変えました

2024-04-28 17:35 UTC, haiiro2gou requested changes

2024-04-28 17:35 UTC, haiiro2gou commented on Asset/data/asset/tags/functions/artifact/give.json
> +        "asset:artifact/0775.jade_armor/give/1.trigger",
重複

2024-04-29 07:32 UTC, Lapis-LJA commented
マスターマージにレビュー内容の修正含まれちゃった

2024-04-29 17:54 UTC, haiiro2gou approved these changes

2024-04-29 17:54 UTC, merged