[Mob156] 侵害の強化とハード対応
ProjectTSB/Asset pull request #82
Opened 2024-01-31 15:46 UTC by Lapis-LJA

2024-02-17 23:55 UTC, Lapis-LJA commented
やる気があったら侵害エフェクトの最大Lvの指定を無くして、付与されるエフェクトのLvを(難易度値-1)に変えたい

2024-02-19 11:04 UTC, Lapis-LJA commented
generic.jump_strengthが来るまでDraftにします

2024-04-29 05:41 UTC, Lapis-LJA commented
1.20.5には対応しない(要約) by Chen ということで後でドラフト解除します

2024-04-29 18:30 UTC, haiiro2gou requested changes

2024-04-29 18:30 UTC, haiiro2gou commented on Asset/data/asset/functions/effect/0612.infringement/register.mcfunction
> +    data modify storage asset:effect Description set value '{"属性耐性が大きく減少し、移動不可になる。"}'
TextComponentがいいなー

2024-04-30 07:16 UTC, haiiro2gou approved these changes

2024-04-30 07:23 UTC, merged