神器963
ProjectTSB/Asset pull request #95
Opened 2024-02-22 02:42 UTC by quikku

2024-03-26 18:07 UTC, haiiro2gou approved these changes
よさげ

2024-04-30 16:03 UTC, haiiro2gou commented on Asset/data/asset/functions/effect/221.hunters_run/modify/add.mcfunction
> +    execute if score $Stack Temporary matches 9 run attribute @s minecraft:generic.movement_speed modifier add 00000001-0000-0003-0000-00dd00000000 "221" 2.15 add
このよくわからん計算式は仕様？

2024-04-30 16:20 UTC, quikku commented on Asset/data/asset/functions/effect/221.hunters_run/modify/add.mcfunction
> +    execute if score $Stack Temporary matches 9 run attribute @s minecraft:generic.movement_speed modifier add 00000001-0000-0003-0000-00dd00000000 "221" 2.15 add
なんだこれ
多分みすってる

2024-04-30 16:22 UTC, haiiro2gou requested changes
一応他と併せてEffect側のディレクトリのid部分を4桁にしてほしいかも
0221みたいな感じ

2024-05-01 16:29 UTC, haiiro2gou requested changes

2024-05-01 16:29 UTC, haiiro2gou commented on Asset/data/asset/functions/effect/0221.hunters_run/register.mcfunction
> +    data modify storage asset:effect Description set value ['{"移動速度が上昇する"}']
```suggestion
    data modify storage asset:effect Description set value ['{"text":"移動速度が上昇する"}']
```

2024-05-02 11:55 UTC, haiiro2gou approved these changes

2024-05-02 13:00 UTC, merged